/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'NIOS_CPU' in SOPC Builder design 'NIOS_SYSTEMV3'
 * SOPC Builder design path: C:/Users/MrBigBear/Desktop/SYSTEMV3/NIOS_SYSTEMV3.sopcinfo
 *
 * Generated: Fri Oct 23 10:18:44 EST 2015
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * ADC_ON configuration
 *
 */

#define ADC_ON_BASE 0x2035d0
#define ADC_ON_BIT_CLEARING_EDGE_REGISTER 0
#define ADC_ON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ADC_ON_CAPTURE 0
#define ADC_ON_DATA_WIDTH 1
#define ADC_ON_DO_TEST_BENCH_WIRING 0
#define ADC_ON_DRIVEN_SIM_VALUE 0
#define ADC_ON_EDGE_TYPE "NONE"
#define ADC_ON_FREQ 70000000
#define ADC_ON_HAS_IN 0
#define ADC_ON_HAS_OUT 1
#define ADC_ON_HAS_TRI 0
#define ADC_ON_IRQ -1
#define ADC_ON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ADC_ON_IRQ_TYPE "NONE"
#define ADC_ON_NAME "/dev/ADC_ON"
#define ADC_ON_RESET_VALUE 0
#define ADC_ON_SPAN 16
#define ADC_ON_TYPE "altera_avalon_pio"
#define ALT_MODULE_CLASS_ADC_ON altera_avalon_pio


/*
 * CH0_PEAK_FOUND configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_PEAK_FOUND altera_avalon_pio
#define CH0_PEAK_FOUND_BASE 0x203510
#define CH0_PEAK_FOUND_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_PEAK_FOUND_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_PEAK_FOUND_CAPTURE 1
#define CH0_PEAK_FOUND_DATA_WIDTH 1
#define CH0_PEAK_FOUND_DO_TEST_BENCH_WIRING 0
#define CH0_PEAK_FOUND_DRIVEN_SIM_VALUE 0
#define CH0_PEAK_FOUND_EDGE_TYPE "RISING"
#define CH0_PEAK_FOUND_FREQ 70000000
#define CH0_PEAK_FOUND_HAS_IN 1
#define CH0_PEAK_FOUND_HAS_OUT 0
#define CH0_PEAK_FOUND_HAS_TRI 0
#define CH0_PEAK_FOUND_IRQ -1
#define CH0_PEAK_FOUND_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_PEAK_FOUND_IRQ_TYPE "NONE"
#define CH0_PEAK_FOUND_NAME "/dev/CH0_PEAK_FOUND"
#define CH0_PEAK_FOUND_RESET_VALUE 0
#define CH0_PEAK_FOUND_SPAN 16
#define CH0_PEAK_FOUND_TYPE "altera_avalon_pio"


/*
 * CH0_RD_PEAK configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_RD_PEAK altera_avalon_pio
#define CH0_RD_PEAK_BASE 0x203520
#define CH0_RD_PEAK_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_RD_PEAK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_RD_PEAK_CAPTURE 0
#define CH0_RD_PEAK_DATA_WIDTH 1
#define CH0_RD_PEAK_DO_TEST_BENCH_WIRING 0
#define CH0_RD_PEAK_DRIVEN_SIM_VALUE 0
#define CH0_RD_PEAK_EDGE_TYPE "NONE"
#define CH0_RD_PEAK_FREQ 70000000
#define CH0_RD_PEAK_HAS_IN 0
#define CH0_RD_PEAK_HAS_OUT 1
#define CH0_RD_PEAK_HAS_TRI 0
#define CH0_RD_PEAK_IRQ -1
#define CH0_RD_PEAK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_RD_PEAK_IRQ_TYPE "NONE"
#define CH0_RD_PEAK_NAME "/dev/CH0_RD_PEAK"
#define CH0_RD_PEAK_RESET_VALUE 0
#define CH0_RD_PEAK_SPAN 16
#define CH0_RD_PEAK_TYPE "altera_avalon_pio"


/*
 * CH0_THRESH configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_THRESH altera_avalon_pio
#define CH0_THRESH_BASE 0x203530
#define CH0_THRESH_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_THRESH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_THRESH_CAPTURE 0
#define CH0_THRESH_DATA_WIDTH 24
#define CH0_THRESH_DO_TEST_BENCH_WIRING 0
#define CH0_THRESH_DRIVEN_SIM_VALUE 0
#define CH0_THRESH_EDGE_TYPE "NONE"
#define CH0_THRESH_FREQ 70000000
#define CH0_THRESH_HAS_IN 0
#define CH0_THRESH_HAS_OUT 1
#define CH0_THRESH_HAS_TRI 0
#define CH0_THRESH_IRQ -1
#define CH0_THRESH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_THRESH_IRQ_TYPE "NONE"
#define CH0_THRESH_NAME "/dev/CH0_THRESH"
#define CH0_THRESH_RESET_VALUE 0
#define CH0_THRESH_SPAN 16
#define CH0_THRESH_TYPE "altera_avalon_pio"


/*
 * CH0_TIME configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_TIME altera_avalon_pio
#define CH0_TIME_BASE 0x2034c0
#define CH0_TIME_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_TIME_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_TIME_CAPTURE 1
#define CH0_TIME_DATA_WIDTH 14
#define CH0_TIME_DO_TEST_BENCH_WIRING 0
#define CH0_TIME_DRIVEN_SIM_VALUE 0
#define CH0_TIME_EDGE_TYPE "RISING"
#define CH0_TIME_FREQ 70000000
#define CH0_TIME_HAS_IN 1
#define CH0_TIME_HAS_OUT 0
#define CH0_TIME_HAS_TRI 0
#define CH0_TIME_IRQ -1
#define CH0_TIME_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_TIME_IRQ_TYPE "NONE"
#define CH0_TIME_NAME "/dev/CH0_TIME"
#define CH0_TIME_RESET_VALUE 0
#define CH0_TIME_SPAN 16
#define CH0_TIME_TYPE "altera_avalon_pio"


/*
 * CH0_TIMER_RST configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_TIMER_RST altera_avalon_pio
#define CH0_TIMER_RST_BASE 0x203580
#define CH0_TIMER_RST_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_TIMER_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_TIMER_RST_CAPTURE 0
#define CH0_TIMER_RST_DATA_WIDTH 1
#define CH0_TIMER_RST_DO_TEST_BENCH_WIRING 0
#define CH0_TIMER_RST_DRIVEN_SIM_VALUE 0
#define CH0_TIMER_RST_EDGE_TYPE "NONE"
#define CH0_TIMER_RST_FREQ 70000000
#define CH0_TIMER_RST_HAS_IN 0
#define CH0_TIMER_RST_HAS_OUT 1
#define CH0_TIMER_RST_HAS_TRI 0
#define CH0_TIMER_RST_IRQ -1
#define CH0_TIMER_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_TIMER_RST_IRQ_TYPE "NONE"
#define CH0_TIMER_RST_NAME "/dev/CH0_TIMER_RST"
#define CH0_TIMER_RST_RESET_VALUE 0
#define CH0_TIMER_RST_SPAN 16
#define CH0_TIMER_RST_TYPE "altera_avalon_pio"


/*
 * CH0_YN1_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN1_L altera_avalon_pio
#define CH0_YN1_L_BASE 0x203500
#define CH0_YN1_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN1_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN1_L_CAPTURE 1
#define CH0_YN1_L_DATA_WIDTH 32
#define CH0_YN1_L_DO_TEST_BENCH_WIRING 0
#define CH0_YN1_L_DRIVEN_SIM_VALUE 0
#define CH0_YN1_L_EDGE_TYPE "RISING"
#define CH0_YN1_L_FREQ 70000000
#define CH0_YN1_L_HAS_IN 1
#define CH0_YN1_L_HAS_OUT 0
#define CH0_YN1_L_HAS_TRI 0
#define CH0_YN1_L_IRQ -1
#define CH0_YN1_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN1_L_IRQ_TYPE "NONE"
#define CH0_YN1_L_NAME "/dev/CH0_YN1_L"
#define CH0_YN1_L_RESET_VALUE 0
#define CH0_YN1_L_SPAN 16
#define CH0_YN1_L_TYPE "altera_avalon_pio"


/*
 * CH0_YN1_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN1_ML altera_avalon_pio
#define CH0_YN1_ML_BASE 0x2034f0
#define CH0_YN1_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN1_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN1_ML_CAPTURE 1
#define CH0_YN1_ML_DATA_WIDTH 32
#define CH0_YN1_ML_DO_TEST_BENCH_WIRING 0
#define CH0_YN1_ML_DRIVEN_SIM_VALUE 0
#define CH0_YN1_ML_EDGE_TYPE "RISING"
#define CH0_YN1_ML_FREQ 70000000
#define CH0_YN1_ML_HAS_IN 1
#define CH0_YN1_ML_HAS_OUT 0
#define CH0_YN1_ML_HAS_TRI 0
#define CH0_YN1_ML_IRQ -1
#define CH0_YN1_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN1_ML_IRQ_TYPE "NONE"
#define CH0_YN1_ML_NAME "/dev/CH0_YN1_ML"
#define CH0_YN1_ML_RESET_VALUE 0
#define CH0_YN1_ML_SPAN 16
#define CH0_YN1_ML_TYPE "altera_avalon_pio"


/*
 * CH0_YN1_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN1_MU altera_avalon_pio
#define CH0_YN1_MU_BASE 0x2034e0
#define CH0_YN1_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN1_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN1_MU_CAPTURE 1
#define CH0_YN1_MU_DATA_WIDTH 32
#define CH0_YN1_MU_DO_TEST_BENCH_WIRING 0
#define CH0_YN1_MU_DRIVEN_SIM_VALUE 0
#define CH0_YN1_MU_EDGE_TYPE "RISING"
#define CH0_YN1_MU_FREQ 70000000
#define CH0_YN1_MU_HAS_IN 1
#define CH0_YN1_MU_HAS_OUT 0
#define CH0_YN1_MU_HAS_TRI 0
#define CH0_YN1_MU_IRQ -1
#define CH0_YN1_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN1_MU_IRQ_TYPE "NONE"
#define CH0_YN1_MU_NAME "/dev/CH0_YN1_MU"
#define CH0_YN1_MU_RESET_VALUE 0
#define CH0_YN1_MU_SPAN 16
#define CH0_YN1_MU_TYPE "altera_avalon_pio"


/*
 * CH0_YN1_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN1_U altera_avalon_pio
#define CH0_YN1_U_BASE 0x2034d0
#define CH0_YN1_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN1_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN1_U_CAPTURE 1
#define CH0_YN1_U_DATA_WIDTH 14
#define CH0_YN1_U_DO_TEST_BENCH_WIRING 0
#define CH0_YN1_U_DRIVEN_SIM_VALUE 0
#define CH0_YN1_U_EDGE_TYPE "RISING"
#define CH0_YN1_U_FREQ 70000000
#define CH0_YN1_U_HAS_IN 1
#define CH0_YN1_U_HAS_OUT 0
#define CH0_YN1_U_HAS_TRI 0
#define CH0_YN1_U_IRQ -1
#define CH0_YN1_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN1_U_IRQ_TYPE "NONE"
#define CH0_YN1_U_NAME "/dev/CH0_YN1_U"
#define CH0_YN1_U_RESET_VALUE 0
#define CH0_YN1_U_SPAN 16
#define CH0_YN1_U_TYPE "altera_avalon_pio"


/*
 * CH0_YN2_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN2_L altera_avalon_pio
#define CH0_YN2_L_BASE 0x203480
#define CH0_YN2_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN2_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN2_L_CAPTURE 1
#define CH0_YN2_L_DATA_WIDTH 32
#define CH0_YN2_L_DO_TEST_BENCH_WIRING 0
#define CH0_YN2_L_DRIVEN_SIM_VALUE 0
#define CH0_YN2_L_EDGE_TYPE "RISING"
#define CH0_YN2_L_FREQ 70000000
#define CH0_YN2_L_HAS_IN 1
#define CH0_YN2_L_HAS_OUT 0
#define CH0_YN2_L_HAS_TRI 0
#define CH0_YN2_L_IRQ -1
#define CH0_YN2_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN2_L_IRQ_TYPE "NONE"
#define CH0_YN2_L_NAME "/dev/CH0_YN2_L"
#define CH0_YN2_L_RESET_VALUE 0
#define CH0_YN2_L_SPAN 16
#define CH0_YN2_L_TYPE "altera_avalon_pio"


/*
 * CH0_YN2_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN2_ML altera_avalon_pio
#define CH0_YN2_ML_BASE 0x2034a0
#define CH0_YN2_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN2_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN2_ML_CAPTURE 1
#define CH0_YN2_ML_DATA_WIDTH 32
#define CH0_YN2_ML_DO_TEST_BENCH_WIRING 0
#define CH0_YN2_ML_DRIVEN_SIM_VALUE 0
#define CH0_YN2_ML_EDGE_TYPE "RISING"
#define CH0_YN2_ML_FREQ 70000000
#define CH0_YN2_ML_HAS_IN 1
#define CH0_YN2_ML_HAS_OUT 0
#define CH0_YN2_ML_HAS_TRI 0
#define CH0_YN2_ML_IRQ -1
#define CH0_YN2_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN2_ML_IRQ_TYPE "NONE"
#define CH0_YN2_ML_NAME "/dev/CH0_YN2_ML"
#define CH0_YN2_ML_RESET_VALUE 0
#define CH0_YN2_ML_SPAN 16
#define CH0_YN2_ML_TYPE "altera_avalon_pio"


/*
 * CH0_YN2_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN2_MU altera_avalon_pio
#define CH0_YN2_MU_BASE 0x2034b0
#define CH0_YN2_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN2_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN2_MU_CAPTURE 1
#define CH0_YN2_MU_DATA_WIDTH 32
#define CH0_YN2_MU_DO_TEST_BENCH_WIRING 0
#define CH0_YN2_MU_DRIVEN_SIM_VALUE 0
#define CH0_YN2_MU_EDGE_TYPE "RISING"
#define CH0_YN2_MU_FREQ 70000000
#define CH0_YN2_MU_HAS_IN 1
#define CH0_YN2_MU_HAS_OUT 0
#define CH0_YN2_MU_HAS_TRI 0
#define CH0_YN2_MU_IRQ -1
#define CH0_YN2_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN2_MU_IRQ_TYPE "NONE"
#define CH0_YN2_MU_NAME "/dev/CH0_YN2_MU"
#define CH0_YN2_MU_RESET_VALUE 0
#define CH0_YN2_MU_SPAN 16
#define CH0_YN2_MU_TYPE "altera_avalon_pio"


/*
 * CH0_YN2_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN2_U altera_avalon_pio
#define CH0_YN2_U_BASE 0x203490
#define CH0_YN2_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN2_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN2_U_CAPTURE 1
#define CH0_YN2_U_DATA_WIDTH 14
#define CH0_YN2_U_DO_TEST_BENCH_WIRING 0
#define CH0_YN2_U_DRIVEN_SIM_VALUE 0
#define CH0_YN2_U_EDGE_TYPE "RISING"
#define CH0_YN2_U_FREQ 70000000
#define CH0_YN2_U_HAS_IN 1
#define CH0_YN2_U_HAS_OUT 0
#define CH0_YN2_U_HAS_TRI 0
#define CH0_YN2_U_IRQ -1
#define CH0_YN2_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN2_U_IRQ_TYPE "NONE"
#define CH0_YN2_U_NAME "/dev/CH0_YN2_U"
#define CH0_YN2_U_RESET_VALUE 0
#define CH0_YN2_U_SPAN 16
#define CH0_YN2_U_TYPE "altera_avalon_pio"


/*
 * CH0_YN3_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN3_L altera_avalon_pio
#define CH0_YN3_L_BASE 0x203470
#define CH0_YN3_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN3_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN3_L_CAPTURE 1
#define CH0_YN3_L_DATA_WIDTH 32
#define CH0_YN3_L_DO_TEST_BENCH_WIRING 0
#define CH0_YN3_L_DRIVEN_SIM_VALUE 0
#define CH0_YN3_L_EDGE_TYPE "RISING"
#define CH0_YN3_L_FREQ 70000000
#define CH0_YN3_L_HAS_IN 1
#define CH0_YN3_L_HAS_OUT 0
#define CH0_YN3_L_HAS_TRI 0
#define CH0_YN3_L_IRQ -1
#define CH0_YN3_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN3_L_IRQ_TYPE "NONE"
#define CH0_YN3_L_NAME "/dev/CH0_YN3_L"
#define CH0_YN3_L_RESET_VALUE 0
#define CH0_YN3_L_SPAN 16
#define CH0_YN3_L_TYPE "altera_avalon_pio"


/*
 * CH0_YN3_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN3_ML altera_avalon_pio
#define CH0_YN3_ML_BASE 0x203460
#define CH0_YN3_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN3_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN3_ML_CAPTURE 1
#define CH0_YN3_ML_DATA_WIDTH 32
#define CH0_YN3_ML_DO_TEST_BENCH_WIRING 0
#define CH0_YN3_ML_DRIVEN_SIM_VALUE 0
#define CH0_YN3_ML_EDGE_TYPE "RISING"
#define CH0_YN3_ML_FREQ 70000000
#define CH0_YN3_ML_HAS_IN 1
#define CH0_YN3_ML_HAS_OUT 0
#define CH0_YN3_ML_HAS_TRI 0
#define CH0_YN3_ML_IRQ -1
#define CH0_YN3_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN3_ML_IRQ_TYPE "NONE"
#define CH0_YN3_ML_NAME "/dev/CH0_YN3_ML"
#define CH0_YN3_ML_RESET_VALUE 0
#define CH0_YN3_ML_SPAN 16
#define CH0_YN3_ML_TYPE "altera_avalon_pio"


/*
 * CH0_YN3_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN3_MU altera_avalon_pio
#define CH0_YN3_MU_BASE 0x203450
#define CH0_YN3_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN3_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN3_MU_CAPTURE 1
#define CH0_YN3_MU_DATA_WIDTH 32
#define CH0_YN3_MU_DO_TEST_BENCH_WIRING 0
#define CH0_YN3_MU_DRIVEN_SIM_VALUE 0
#define CH0_YN3_MU_EDGE_TYPE "RISING"
#define CH0_YN3_MU_FREQ 70000000
#define CH0_YN3_MU_HAS_IN 1
#define CH0_YN3_MU_HAS_OUT 0
#define CH0_YN3_MU_HAS_TRI 0
#define CH0_YN3_MU_IRQ -1
#define CH0_YN3_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN3_MU_IRQ_TYPE "NONE"
#define CH0_YN3_MU_NAME "/dev/CH0_YN3_MU"
#define CH0_YN3_MU_RESET_VALUE 0
#define CH0_YN3_MU_SPAN 16
#define CH0_YN3_MU_TYPE "altera_avalon_pio"


/*
 * CH0_YN3_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH0_YN3_U altera_avalon_pio
#define CH0_YN3_U_BASE 0x203440
#define CH0_YN3_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH0_YN3_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH0_YN3_U_CAPTURE 1
#define CH0_YN3_U_DATA_WIDTH 14
#define CH0_YN3_U_DO_TEST_BENCH_WIRING 0
#define CH0_YN3_U_DRIVEN_SIM_VALUE 0
#define CH0_YN3_U_EDGE_TYPE "RISING"
#define CH0_YN3_U_FREQ 70000000
#define CH0_YN3_U_HAS_IN 1
#define CH0_YN3_U_HAS_OUT 0
#define CH0_YN3_U_HAS_TRI 0
#define CH0_YN3_U_IRQ -1
#define CH0_YN3_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH0_YN3_U_IRQ_TYPE "NONE"
#define CH0_YN3_U_NAME "/dev/CH0_YN3_U"
#define CH0_YN3_U_RESET_VALUE 0
#define CH0_YN3_U_SPAN 16
#define CH0_YN3_U_TYPE "altera_avalon_pio"


/*
 * CH1_PEAK_FOUND configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_PEAK_FOUND altera_avalon_pio
#define CH1_PEAK_FOUND_BASE 0x203400
#define CH1_PEAK_FOUND_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_PEAK_FOUND_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_PEAK_FOUND_CAPTURE 1
#define CH1_PEAK_FOUND_DATA_WIDTH 1
#define CH1_PEAK_FOUND_DO_TEST_BENCH_WIRING 0
#define CH1_PEAK_FOUND_DRIVEN_SIM_VALUE 0
#define CH1_PEAK_FOUND_EDGE_TYPE "RISING"
#define CH1_PEAK_FOUND_FREQ 70000000
#define CH1_PEAK_FOUND_HAS_IN 1
#define CH1_PEAK_FOUND_HAS_OUT 0
#define CH1_PEAK_FOUND_HAS_TRI 0
#define CH1_PEAK_FOUND_IRQ -1
#define CH1_PEAK_FOUND_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_PEAK_FOUND_IRQ_TYPE "NONE"
#define CH1_PEAK_FOUND_NAME "/dev/CH1_PEAK_FOUND"
#define CH1_PEAK_FOUND_RESET_VALUE 0
#define CH1_PEAK_FOUND_SPAN 16
#define CH1_PEAK_FOUND_TYPE "altera_avalon_pio"


/*
 * CH1_RD_PEAK configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_RD_PEAK altera_avalon_pio
#define CH1_RD_PEAK_BASE 0x203410
#define CH1_RD_PEAK_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_RD_PEAK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_RD_PEAK_CAPTURE 0
#define CH1_RD_PEAK_DATA_WIDTH 1
#define CH1_RD_PEAK_DO_TEST_BENCH_WIRING 0
#define CH1_RD_PEAK_DRIVEN_SIM_VALUE 0
#define CH1_RD_PEAK_EDGE_TYPE "NONE"
#define CH1_RD_PEAK_FREQ 70000000
#define CH1_RD_PEAK_HAS_IN 0
#define CH1_RD_PEAK_HAS_OUT 1
#define CH1_RD_PEAK_HAS_TRI 0
#define CH1_RD_PEAK_IRQ -1
#define CH1_RD_PEAK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_RD_PEAK_IRQ_TYPE "NONE"
#define CH1_RD_PEAK_NAME "/dev/CH1_RD_PEAK"
#define CH1_RD_PEAK_RESET_VALUE 0
#define CH1_RD_PEAK_SPAN 16
#define CH1_RD_PEAK_TYPE "altera_avalon_pio"


/*
 * CH1_THRESH configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_THRESH altera_avalon_pio
#define CH1_THRESH_BASE 0x203420
#define CH1_THRESH_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_THRESH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_THRESH_CAPTURE 0
#define CH1_THRESH_DATA_WIDTH 24
#define CH1_THRESH_DO_TEST_BENCH_WIRING 0
#define CH1_THRESH_DRIVEN_SIM_VALUE 0
#define CH1_THRESH_EDGE_TYPE "NONE"
#define CH1_THRESH_FREQ 70000000
#define CH1_THRESH_HAS_IN 0
#define CH1_THRESH_HAS_OUT 1
#define CH1_THRESH_HAS_TRI 0
#define CH1_THRESH_IRQ -1
#define CH1_THRESH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_THRESH_IRQ_TYPE "NONE"
#define CH1_THRESH_NAME "/dev/CH1_THRESH"
#define CH1_THRESH_RESET_VALUE 0
#define CH1_THRESH_SPAN 16
#define CH1_THRESH_TYPE "altera_avalon_pio"


/*
 * CH1_TIME configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_TIME altera_avalon_pio
#define CH1_TIME_BASE 0x2033f0
#define CH1_TIME_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_TIME_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_TIME_CAPTURE 1
#define CH1_TIME_DATA_WIDTH 14
#define CH1_TIME_DO_TEST_BENCH_WIRING 0
#define CH1_TIME_DRIVEN_SIM_VALUE 0
#define CH1_TIME_EDGE_TYPE "RISING"
#define CH1_TIME_FREQ 70000000
#define CH1_TIME_HAS_IN 1
#define CH1_TIME_HAS_OUT 0
#define CH1_TIME_HAS_TRI 0
#define CH1_TIME_IRQ -1
#define CH1_TIME_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_TIME_IRQ_TYPE "NONE"
#define CH1_TIME_NAME "/dev/CH1_TIME"
#define CH1_TIME_RESET_VALUE 0
#define CH1_TIME_SPAN 16
#define CH1_TIME_TYPE "altera_avalon_pio"


/*
 * CH1_TIMER_RST configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_TIMER_RST altera_avalon_pio
#define CH1_TIMER_RST_BASE 0x203430
#define CH1_TIMER_RST_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_TIMER_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_TIMER_RST_CAPTURE 0
#define CH1_TIMER_RST_DATA_WIDTH 1
#define CH1_TIMER_RST_DO_TEST_BENCH_WIRING 0
#define CH1_TIMER_RST_DRIVEN_SIM_VALUE 0
#define CH1_TIMER_RST_EDGE_TYPE "NONE"
#define CH1_TIMER_RST_FREQ 70000000
#define CH1_TIMER_RST_HAS_IN 0
#define CH1_TIMER_RST_HAS_OUT 1
#define CH1_TIMER_RST_HAS_TRI 0
#define CH1_TIMER_RST_IRQ -1
#define CH1_TIMER_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_TIMER_RST_IRQ_TYPE "NONE"
#define CH1_TIMER_RST_NAME "/dev/CH1_TIMER_RST"
#define CH1_TIMER_RST_RESET_VALUE 0
#define CH1_TIMER_RST_SPAN 16
#define CH1_TIMER_RST_TYPE "altera_avalon_pio"


/*
 * CH1_YN1_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN1_L altera_avalon_pio
#define CH1_YN1_L_BASE 0x2033b0
#define CH1_YN1_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN1_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN1_L_CAPTURE 1
#define CH1_YN1_L_DATA_WIDTH 32
#define CH1_YN1_L_DO_TEST_BENCH_WIRING 0
#define CH1_YN1_L_DRIVEN_SIM_VALUE 0
#define CH1_YN1_L_EDGE_TYPE "RISING"
#define CH1_YN1_L_FREQ 70000000
#define CH1_YN1_L_HAS_IN 1
#define CH1_YN1_L_HAS_OUT 0
#define CH1_YN1_L_HAS_TRI 0
#define CH1_YN1_L_IRQ -1
#define CH1_YN1_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN1_L_IRQ_TYPE "NONE"
#define CH1_YN1_L_NAME "/dev/CH1_YN1_L"
#define CH1_YN1_L_RESET_VALUE 0
#define CH1_YN1_L_SPAN 16
#define CH1_YN1_L_TYPE "altera_avalon_pio"


/*
 * CH1_YN1_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN1_ML altera_avalon_pio
#define CH1_YN1_ML_BASE 0x2033c0
#define CH1_YN1_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN1_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN1_ML_CAPTURE 1
#define CH1_YN1_ML_DATA_WIDTH 32
#define CH1_YN1_ML_DO_TEST_BENCH_WIRING 0
#define CH1_YN1_ML_DRIVEN_SIM_VALUE 0
#define CH1_YN1_ML_EDGE_TYPE "RISING"
#define CH1_YN1_ML_FREQ 70000000
#define CH1_YN1_ML_HAS_IN 1
#define CH1_YN1_ML_HAS_OUT 0
#define CH1_YN1_ML_HAS_TRI 0
#define CH1_YN1_ML_IRQ -1
#define CH1_YN1_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN1_ML_IRQ_TYPE "NONE"
#define CH1_YN1_ML_NAME "/dev/CH1_YN1_ML"
#define CH1_YN1_ML_RESET_VALUE 0
#define CH1_YN1_ML_SPAN 16
#define CH1_YN1_ML_TYPE "altera_avalon_pio"


/*
 * CH1_YN1_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN1_MU altera_avalon_pio
#define CH1_YN1_MU_BASE 0x2033d0
#define CH1_YN1_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN1_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN1_MU_CAPTURE 1
#define CH1_YN1_MU_DATA_WIDTH 32
#define CH1_YN1_MU_DO_TEST_BENCH_WIRING 0
#define CH1_YN1_MU_DRIVEN_SIM_VALUE 0
#define CH1_YN1_MU_EDGE_TYPE "RISING"
#define CH1_YN1_MU_FREQ 70000000
#define CH1_YN1_MU_HAS_IN 1
#define CH1_YN1_MU_HAS_OUT 0
#define CH1_YN1_MU_HAS_TRI 0
#define CH1_YN1_MU_IRQ -1
#define CH1_YN1_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN1_MU_IRQ_TYPE "NONE"
#define CH1_YN1_MU_NAME "/dev/CH1_YN1_MU"
#define CH1_YN1_MU_RESET_VALUE 0
#define CH1_YN1_MU_SPAN 16
#define CH1_YN1_MU_TYPE "altera_avalon_pio"


/*
 * CH1_YN1_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN1_U altera_avalon_pio
#define CH1_YN1_U_BASE 0x2033e0
#define CH1_YN1_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN1_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN1_U_CAPTURE 1
#define CH1_YN1_U_DATA_WIDTH 14
#define CH1_YN1_U_DO_TEST_BENCH_WIRING 0
#define CH1_YN1_U_DRIVEN_SIM_VALUE 0
#define CH1_YN1_U_EDGE_TYPE "RISING"
#define CH1_YN1_U_FREQ 70000000
#define CH1_YN1_U_HAS_IN 1
#define CH1_YN1_U_HAS_OUT 0
#define CH1_YN1_U_HAS_TRI 0
#define CH1_YN1_U_IRQ -1
#define CH1_YN1_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN1_U_IRQ_TYPE "NONE"
#define CH1_YN1_U_NAME "/dev/CH1_YN1_U"
#define CH1_YN1_U_RESET_VALUE 0
#define CH1_YN1_U_SPAN 16
#define CH1_YN1_U_TYPE "altera_avalon_pio"


/*
 * CH1_YN2_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN2_L altera_avalon_pio
#define CH1_YN2_L_BASE 0x203370
#define CH1_YN2_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN2_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN2_L_CAPTURE 1
#define CH1_YN2_L_DATA_WIDTH 32
#define CH1_YN2_L_DO_TEST_BENCH_WIRING 0
#define CH1_YN2_L_DRIVEN_SIM_VALUE 0
#define CH1_YN2_L_EDGE_TYPE "RISING"
#define CH1_YN2_L_FREQ 70000000
#define CH1_YN2_L_HAS_IN 1
#define CH1_YN2_L_HAS_OUT 0
#define CH1_YN2_L_HAS_TRI 0
#define CH1_YN2_L_IRQ -1
#define CH1_YN2_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN2_L_IRQ_TYPE "NONE"
#define CH1_YN2_L_NAME "/dev/CH1_YN2_L"
#define CH1_YN2_L_RESET_VALUE 0
#define CH1_YN2_L_SPAN 16
#define CH1_YN2_L_TYPE "altera_avalon_pio"


/*
 * CH1_YN2_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN2_ML altera_avalon_pio
#define CH1_YN2_ML_BASE 0x203380
#define CH1_YN2_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN2_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN2_ML_CAPTURE 1
#define CH1_YN2_ML_DATA_WIDTH 32
#define CH1_YN2_ML_DO_TEST_BENCH_WIRING 0
#define CH1_YN2_ML_DRIVEN_SIM_VALUE 0
#define CH1_YN2_ML_EDGE_TYPE "RISING"
#define CH1_YN2_ML_FREQ 70000000
#define CH1_YN2_ML_HAS_IN 1
#define CH1_YN2_ML_HAS_OUT 0
#define CH1_YN2_ML_HAS_TRI 0
#define CH1_YN2_ML_IRQ -1
#define CH1_YN2_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN2_ML_IRQ_TYPE "NONE"
#define CH1_YN2_ML_NAME "/dev/CH1_YN2_ML"
#define CH1_YN2_ML_RESET_VALUE 0
#define CH1_YN2_ML_SPAN 16
#define CH1_YN2_ML_TYPE "altera_avalon_pio"


/*
 * CH1_YN2_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN2_MU altera_avalon_pio
#define CH1_YN2_MU_BASE 0x203390
#define CH1_YN2_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN2_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN2_MU_CAPTURE 1
#define CH1_YN2_MU_DATA_WIDTH 32
#define CH1_YN2_MU_DO_TEST_BENCH_WIRING 0
#define CH1_YN2_MU_DRIVEN_SIM_VALUE 0
#define CH1_YN2_MU_EDGE_TYPE "RISING"
#define CH1_YN2_MU_FREQ 70000000
#define CH1_YN2_MU_HAS_IN 1
#define CH1_YN2_MU_HAS_OUT 0
#define CH1_YN2_MU_HAS_TRI 0
#define CH1_YN2_MU_IRQ -1
#define CH1_YN2_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN2_MU_IRQ_TYPE "NONE"
#define CH1_YN2_MU_NAME "/dev/CH1_YN2_MU"
#define CH1_YN2_MU_RESET_VALUE 0
#define CH1_YN2_MU_SPAN 16
#define CH1_YN2_MU_TYPE "altera_avalon_pio"


/*
 * CH1_YN2_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN2_U altera_avalon_pio
#define CH1_YN2_U_BASE 0x2033a0
#define CH1_YN2_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN2_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN2_U_CAPTURE 1
#define CH1_YN2_U_DATA_WIDTH 14
#define CH1_YN2_U_DO_TEST_BENCH_WIRING 0
#define CH1_YN2_U_DRIVEN_SIM_VALUE 0
#define CH1_YN2_U_EDGE_TYPE "RISING"
#define CH1_YN2_U_FREQ 70000000
#define CH1_YN2_U_HAS_IN 1
#define CH1_YN2_U_HAS_OUT 0
#define CH1_YN2_U_HAS_TRI 0
#define CH1_YN2_U_IRQ -1
#define CH1_YN2_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN2_U_IRQ_TYPE "NONE"
#define CH1_YN2_U_NAME "/dev/CH1_YN2_U"
#define CH1_YN2_U_RESET_VALUE 0
#define CH1_YN2_U_SPAN 16
#define CH1_YN2_U_TYPE "altera_avalon_pio"


/*
 * CH1_YN3_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN3_L altera_avalon_pio
#define CH1_YN3_L_BASE 0x203330
#define CH1_YN3_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN3_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN3_L_CAPTURE 1
#define CH1_YN3_L_DATA_WIDTH 32
#define CH1_YN3_L_DO_TEST_BENCH_WIRING 0
#define CH1_YN3_L_DRIVEN_SIM_VALUE 0
#define CH1_YN3_L_EDGE_TYPE "RISING"
#define CH1_YN3_L_FREQ 70000000
#define CH1_YN3_L_HAS_IN 1
#define CH1_YN3_L_HAS_OUT 0
#define CH1_YN3_L_HAS_TRI 0
#define CH1_YN3_L_IRQ -1
#define CH1_YN3_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN3_L_IRQ_TYPE "NONE"
#define CH1_YN3_L_NAME "/dev/CH1_YN3_L"
#define CH1_YN3_L_RESET_VALUE 0
#define CH1_YN3_L_SPAN 16
#define CH1_YN3_L_TYPE "altera_avalon_pio"


/*
 * CH1_YN3_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN3_ML altera_avalon_pio
#define CH1_YN3_ML_BASE 0x203340
#define CH1_YN3_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN3_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN3_ML_CAPTURE 1
#define CH1_YN3_ML_DATA_WIDTH 32
#define CH1_YN3_ML_DO_TEST_BENCH_WIRING 0
#define CH1_YN3_ML_DRIVEN_SIM_VALUE 0
#define CH1_YN3_ML_EDGE_TYPE "RISING"
#define CH1_YN3_ML_FREQ 70000000
#define CH1_YN3_ML_HAS_IN 1
#define CH1_YN3_ML_HAS_OUT 0
#define CH1_YN3_ML_HAS_TRI 0
#define CH1_YN3_ML_IRQ -1
#define CH1_YN3_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN3_ML_IRQ_TYPE "NONE"
#define CH1_YN3_ML_NAME "/dev/CH1_YN3_ML"
#define CH1_YN3_ML_RESET_VALUE 0
#define CH1_YN3_ML_SPAN 16
#define CH1_YN3_ML_TYPE "altera_avalon_pio"


/*
 * CH1_YN3_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN3_MU altera_avalon_pio
#define CH1_YN3_MU_BASE 0x203350
#define CH1_YN3_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN3_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN3_MU_CAPTURE 1
#define CH1_YN3_MU_DATA_WIDTH 32
#define CH1_YN3_MU_DO_TEST_BENCH_WIRING 0
#define CH1_YN3_MU_DRIVEN_SIM_VALUE 0
#define CH1_YN3_MU_EDGE_TYPE "RISING"
#define CH1_YN3_MU_FREQ 70000000
#define CH1_YN3_MU_HAS_IN 1
#define CH1_YN3_MU_HAS_OUT 0
#define CH1_YN3_MU_HAS_TRI 0
#define CH1_YN3_MU_IRQ -1
#define CH1_YN3_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN3_MU_IRQ_TYPE "NONE"
#define CH1_YN3_MU_NAME "/dev/CH1_YN3_MU"
#define CH1_YN3_MU_RESET_VALUE 0
#define CH1_YN3_MU_SPAN 16
#define CH1_YN3_MU_TYPE "altera_avalon_pio"


/*
 * CH1_YN3_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH1_YN3_U altera_avalon_pio
#define CH1_YN3_U_BASE 0x203360
#define CH1_YN3_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH1_YN3_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH1_YN3_U_CAPTURE 1
#define CH1_YN3_U_DATA_WIDTH 14
#define CH1_YN3_U_DO_TEST_BENCH_WIRING 0
#define CH1_YN3_U_DRIVEN_SIM_VALUE 0
#define CH1_YN3_U_EDGE_TYPE "RISING"
#define CH1_YN3_U_FREQ 70000000
#define CH1_YN3_U_HAS_IN 1
#define CH1_YN3_U_HAS_OUT 0
#define CH1_YN3_U_HAS_TRI 0
#define CH1_YN3_U_IRQ -1
#define CH1_YN3_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH1_YN3_U_IRQ_TYPE "NONE"
#define CH1_YN3_U_NAME "/dev/CH1_YN3_U"
#define CH1_YN3_U_RESET_VALUE 0
#define CH1_YN3_U_SPAN 16
#define CH1_YN3_U_TYPE "altera_avalon_pio"


/*
 * CH2_PEAK_FOUND configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_PEAK_FOUND altera_avalon_pio
#define CH2_PEAK_FOUND_BASE 0x2032f0
#define CH2_PEAK_FOUND_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_PEAK_FOUND_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_PEAK_FOUND_CAPTURE 1
#define CH2_PEAK_FOUND_DATA_WIDTH 1
#define CH2_PEAK_FOUND_DO_TEST_BENCH_WIRING 0
#define CH2_PEAK_FOUND_DRIVEN_SIM_VALUE 0
#define CH2_PEAK_FOUND_EDGE_TYPE "RISING"
#define CH2_PEAK_FOUND_FREQ 70000000
#define CH2_PEAK_FOUND_HAS_IN 1
#define CH2_PEAK_FOUND_HAS_OUT 0
#define CH2_PEAK_FOUND_HAS_TRI 0
#define CH2_PEAK_FOUND_IRQ -1
#define CH2_PEAK_FOUND_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_PEAK_FOUND_IRQ_TYPE "NONE"
#define CH2_PEAK_FOUND_NAME "/dev/CH2_PEAK_FOUND"
#define CH2_PEAK_FOUND_RESET_VALUE 0
#define CH2_PEAK_FOUND_SPAN 16
#define CH2_PEAK_FOUND_TYPE "altera_avalon_pio"


/*
 * CH2_RD_PEAK configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_RD_PEAK altera_avalon_pio
#define CH2_RD_PEAK_BASE 0x203300
#define CH2_RD_PEAK_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_RD_PEAK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_RD_PEAK_CAPTURE 0
#define CH2_RD_PEAK_DATA_WIDTH 1
#define CH2_RD_PEAK_DO_TEST_BENCH_WIRING 0
#define CH2_RD_PEAK_DRIVEN_SIM_VALUE 0
#define CH2_RD_PEAK_EDGE_TYPE "NONE"
#define CH2_RD_PEAK_FREQ 70000000
#define CH2_RD_PEAK_HAS_IN 0
#define CH2_RD_PEAK_HAS_OUT 1
#define CH2_RD_PEAK_HAS_TRI 0
#define CH2_RD_PEAK_IRQ -1
#define CH2_RD_PEAK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_RD_PEAK_IRQ_TYPE "NONE"
#define CH2_RD_PEAK_NAME "/dev/CH2_RD_PEAK"
#define CH2_RD_PEAK_RESET_VALUE 0
#define CH2_RD_PEAK_SPAN 16
#define CH2_RD_PEAK_TYPE "altera_avalon_pio"


/*
 * CH2_THRESH configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_THRESH altera_avalon_pio
#define CH2_THRESH_BASE 0x203310
#define CH2_THRESH_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_THRESH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_THRESH_CAPTURE 0
#define CH2_THRESH_DATA_WIDTH 24
#define CH2_THRESH_DO_TEST_BENCH_WIRING 0
#define CH2_THRESH_DRIVEN_SIM_VALUE 0
#define CH2_THRESH_EDGE_TYPE "NONE"
#define CH2_THRESH_FREQ 70000000
#define CH2_THRESH_HAS_IN 0
#define CH2_THRESH_HAS_OUT 1
#define CH2_THRESH_HAS_TRI 0
#define CH2_THRESH_IRQ -1
#define CH2_THRESH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_THRESH_IRQ_TYPE "NONE"
#define CH2_THRESH_NAME "/dev/CH2_THRESH"
#define CH2_THRESH_RESET_VALUE 0
#define CH2_THRESH_SPAN 16
#define CH2_THRESH_TYPE "altera_avalon_pio"


/*
 * CH2_TIME configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_TIME altera_avalon_pio
#define CH2_TIME_BASE 0x2032e0
#define CH2_TIME_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_TIME_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_TIME_CAPTURE 1
#define CH2_TIME_DATA_WIDTH 14
#define CH2_TIME_DO_TEST_BENCH_WIRING 0
#define CH2_TIME_DRIVEN_SIM_VALUE 0
#define CH2_TIME_EDGE_TYPE "RISING"
#define CH2_TIME_FREQ 70000000
#define CH2_TIME_HAS_IN 1
#define CH2_TIME_HAS_OUT 0
#define CH2_TIME_HAS_TRI 0
#define CH2_TIME_IRQ -1
#define CH2_TIME_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_TIME_IRQ_TYPE "NONE"
#define CH2_TIME_NAME "/dev/CH2_TIME"
#define CH2_TIME_RESET_VALUE 0
#define CH2_TIME_SPAN 16
#define CH2_TIME_TYPE "altera_avalon_pio"


/*
 * CH2_TIMER_RST configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_TIMER_RST altera_avalon_pio
#define CH2_TIMER_RST_BASE 0x203320
#define CH2_TIMER_RST_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_TIMER_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_TIMER_RST_CAPTURE 0
#define CH2_TIMER_RST_DATA_WIDTH 1
#define CH2_TIMER_RST_DO_TEST_BENCH_WIRING 0
#define CH2_TIMER_RST_DRIVEN_SIM_VALUE 0
#define CH2_TIMER_RST_EDGE_TYPE "NONE"
#define CH2_TIMER_RST_FREQ 70000000
#define CH2_TIMER_RST_HAS_IN 0
#define CH2_TIMER_RST_HAS_OUT 1
#define CH2_TIMER_RST_HAS_TRI 0
#define CH2_TIMER_RST_IRQ -1
#define CH2_TIMER_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_TIMER_RST_IRQ_TYPE "NONE"
#define CH2_TIMER_RST_NAME "/dev/CH2_TIMER_RST"
#define CH2_TIMER_RST_RESET_VALUE 0
#define CH2_TIMER_RST_SPAN 16
#define CH2_TIMER_RST_TYPE "altera_avalon_pio"


/*
 * CH2_YN1_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN1_L altera_avalon_pio
#define CH2_YN1_L_BASE 0x2032a0
#define CH2_YN1_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN1_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN1_L_CAPTURE 1
#define CH2_YN1_L_DATA_WIDTH 32
#define CH2_YN1_L_DO_TEST_BENCH_WIRING 0
#define CH2_YN1_L_DRIVEN_SIM_VALUE 0
#define CH2_YN1_L_EDGE_TYPE "RISING"
#define CH2_YN1_L_FREQ 70000000
#define CH2_YN1_L_HAS_IN 1
#define CH2_YN1_L_HAS_OUT 0
#define CH2_YN1_L_HAS_TRI 0
#define CH2_YN1_L_IRQ -1
#define CH2_YN1_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN1_L_IRQ_TYPE "NONE"
#define CH2_YN1_L_NAME "/dev/CH2_YN1_L"
#define CH2_YN1_L_RESET_VALUE 0
#define CH2_YN1_L_SPAN 16
#define CH2_YN1_L_TYPE "altera_avalon_pio"


/*
 * CH2_YN1_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN1_ML altera_avalon_pio
#define CH2_YN1_ML_BASE 0x2032b0
#define CH2_YN1_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN1_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN1_ML_CAPTURE 1
#define CH2_YN1_ML_DATA_WIDTH 32
#define CH2_YN1_ML_DO_TEST_BENCH_WIRING 0
#define CH2_YN1_ML_DRIVEN_SIM_VALUE 0
#define CH2_YN1_ML_EDGE_TYPE "RISING"
#define CH2_YN1_ML_FREQ 70000000
#define CH2_YN1_ML_HAS_IN 1
#define CH2_YN1_ML_HAS_OUT 0
#define CH2_YN1_ML_HAS_TRI 0
#define CH2_YN1_ML_IRQ -1
#define CH2_YN1_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN1_ML_IRQ_TYPE "NONE"
#define CH2_YN1_ML_NAME "/dev/CH2_YN1_ML"
#define CH2_YN1_ML_RESET_VALUE 0
#define CH2_YN1_ML_SPAN 16
#define CH2_YN1_ML_TYPE "altera_avalon_pio"


/*
 * CH2_YN1_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN1_MU altera_avalon_pio
#define CH2_YN1_MU_BASE 0x2032c0
#define CH2_YN1_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN1_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN1_MU_CAPTURE 1
#define CH2_YN1_MU_DATA_WIDTH 32
#define CH2_YN1_MU_DO_TEST_BENCH_WIRING 0
#define CH2_YN1_MU_DRIVEN_SIM_VALUE 0
#define CH2_YN1_MU_EDGE_TYPE "RISING"
#define CH2_YN1_MU_FREQ 70000000
#define CH2_YN1_MU_HAS_IN 1
#define CH2_YN1_MU_HAS_OUT 0
#define CH2_YN1_MU_HAS_TRI 0
#define CH2_YN1_MU_IRQ -1
#define CH2_YN1_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN1_MU_IRQ_TYPE "NONE"
#define CH2_YN1_MU_NAME "/dev/CH2_YN1_MU"
#define CH2_YN1_MU_RESET_VALUE 0
#define CH2_YN1_MU_SPAN 16
#define CH2_YN1_MU_TYPE "altera_avalon_pio"


/*
 * CH2_YN1_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN1_U altera_avalon_pio
#define CH2_YN1_U_BASE 0x2032d0
#define CH2_YN1_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN1_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN1_U_CAPTURE 1
#define CH2_YN1_U_DATA_WIDTH 14
#define CH2_YN1_U_DO_TEST_BENCH_WIRING 0
#define CH2_YN1_U_DRIVEN_SIM_VALUE 0
#define CH2_YN1_U_EDGE_TYPE "RISING"
#define CH2_YN1_U_FREQ 70000000
#define CH2_YN1_U_HAS_IN 1
#define CH2_YN1_U_HAS_OUT 0
#define CH2_YN1_U_HAS_TRI 0
#define CH2_YN1_U_IRQ -1
#define CH2_YN1_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN1_U_IRQ_TYPE "NONE"
#define CH2_YN1_U_NAME "/dev/CH2_YN1_U"
#define CH2_YN1_U_RESET_VALUE 0
#define CH2_YN1_U_SPAN 16
#define CH2_YN1_U_TYPE "altera_avalon_pio"


/*
 * CH2_YN2_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN2_L altera_avalon_pio
#define CH2_YN2_L_BASE 0x203260
#define CH2_YN2_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN2_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN2_L_CAPTURE 1
#define CH2_YN2_L_DATA_WIDTH 32
#define CH2_YN2_L_DO_TEST_BENCH_WIRING 0
#define CH2_YN2_L_DRIVEN_SIM_VALUE 0
#define CH2_YN2_L_EDGE_TYPE "RISING"
#define CH2_YN2_L_FREQ 70000000
#define CH2_YN2_L_HAS_IN 1
#define CH2_YN2_L_HAS_OUT 0
#define CH2_YN2_L_HAS_TRI 0
#define CH2_YN2_L_IRQ -1
#define CH2_YN2_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN2_L_IRQ_TYPE "NONE"
#define CH2_YN2_L_NAME "/dev/CH2_YN2_L"
#define CH2_YN2_L_RESET_VALUE 0
#define CH2_YN2_L_SPAN 16
#define CH2_YN2_L_TYPE "altera_avalon_pio"


/*
 * CH2_YN2_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN2_ML altera_avalon_pio
#define CH2_YN2_ML_BASE 0x203270
#define CH2_YN2_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN2_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN2_ML_CAPTURE 1
#define CH2_YN2_ML_DATA_WIDTH 32
#define CH2_YN2_ML_DO_TEST_BENCH_WIRING 0
#define CH2_YN2_ML_DRIVEN_SIM_VALUE 0
#define CH2_YN2_ML_EDGE_TYPE "RISING"
#define CH2_YN2_ML_FREQ 70000000
#define CH2_YN2_ML_HAS_IN 1
#define CH2_YN2_ML_HAS_OUT 0
#define CH2_YN2_ML_HAS_TRI 0
#define CH2_YN2_ML_IRQ -1
#define CH2_YN2_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN2_ML_IRQ_TYPE "NONE"
#define CH2_YN2_ML_NAME "/dev/CH2_YN2_ML"
#define CH2_YN2_ML_RESET_VALUE 0
#define CH2_YN2_ML_SPAN 16
#define CH2_YN2_ML_TYPE "altera_avalon_pio"


/*
 * CH2_YN2_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN2_MU altera_avalon_pio
#define CH2_YN2_MU_BASE 0x203280
#define CH2_YN2_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN2_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN2_MU_CAPTURE 1
#define CH2_YN2_MU_DATA_WIDTH 32
#define CH2_YN2_MU_DO_TEST_BENCH_WIRING 0
#define CH2_YN2_MU_DRIVEN_SIM_VALUE 0
#define CH2_YN2_MU_EDGE_TYPE "RISING"
#define CH2_YN2_MU_FREQ 70000000
#define CH2_YN2_MU_HAS_IN 1
#define CH2_YN2_MU_HAS_OUT 0
#define CH2_YN2_MU_HAS_TRI 0
#define CH2_YN2_MU_IRQ -1
#define CH2_YN2_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN2_MU_IRQ_TYPE "NONE"
#define CH2_YN2_MU_NAME "/dev/CH2_YN2_MU"
#define CH2_YN2_MU_RESET_VALUE 0
#define CH2_YN2_MU_SPAN 16
#define CH2_YN2_MU_TYPE "altera_avalon_pio"


/*
 * CH2_YN2_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN2_U altera_avalon_pio
#define CH2_YN2_U_BASE 0x203290
#define CH2_YN2_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN2_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN2_U_CAPTURE 1
#define CH2_YN2_U_DATA_WIDTH 14
#define CH2_YN2_U_DO_TEST_BENCH_WIRING 0
#define CH2_YN2_U_DRIVEN_SIM_VALUE 0
#define CH2_YN2_U_EDGE_TYPE "RISING"
#define CH2_YN2_U_FREQ 70000000
#define CH2_YN2_U_HAS_IN 1
#define CH2_YN2_U_HAS_OUT 0
#define CH2_YN2_U_HAS_TRI 0
#define CH2_YN2_U_IRQ -1
#define CH2_YN2_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN2_U_IRQ_TYPE "NONE"
#define CH2_YN2_U_NAME "/dev/CH2_YN2_U"
#define CH2_YN2_U_RESET_VALUE 0
#define CH2_YN2_U_SPAN 16
#define CH2_YN2_U_TYPE "altera_avalon_pio"


/*
 * CH2_YN3_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN3_L altera_avalon_pio
#define CH2_YN3_L_BASE 0x203220
#define CH2_YN3_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN3_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN3_L_CAPTURE 1
#define CH2_YN3_L_DATA_WIDTH 32
#define CH2_YN3_L_DO_TEST_BENCH_WIRING 0
#define CH2_YN3_L_DRIVEN_SIM_VALUE 0
#define CH2_YN3_L_EDGE_TYPE "RISING"
#define CH2_YN3_L_FREQ 70000000
#define CH2_YN3_L_HAS_IN 1
#define CH2_YN3_L_HAS_OUT 0
#define CH2_YN3_L_HAS_TRI 0
#define CH2_YN3_L_IRQ -1
#define CH2_YN3_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN3_L_IRQ_TYPE "NONE"
#define CH2_YN3_L_NAME "/dev/CH2_YN3_L"
#define CH2_YN3_L_RESET_VALUE 0
#define CH2_YN3_L_SPAN 16
#define CH2_YN3_L_TYPE "altera_avalon_pio"


/*
 * CH2_YN3_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN3_ML altera_avalon_pio
#define CH2_YN3_ML_BASE 0x203230
#define CH2_YN3_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN3_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN3_ML_CAPTURE 1
#define CH2_YN3_ML_DATA_WIDTH 32
#define CH2_YN3_ML_DO_TEST_BENCH_WIRING 0
#define CH2_YN3_ML_DRIVEN_SIM_VALUE 0
#define CH2_YN3_ML_EDGE_TYPE "RISING"
#define CH2_YN3_ML_FREQ 70000000
#define CH2_YN3_ML_HAS_IN 1
#define CH2_YN3_ML_HAS_OUT 0
#define CH2_YN3_ML_HAS_TRI 0
#define CH2_YN3_ML_IRQ -1
#define CH2_YN3_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN3_ML_IRQ_TYPE "NONE"
#define CH2_YN3_ML_NAME "/dev/CH2_YN3_ML"
#define CH2_YN3_ML_RESET_VALUE 0
#define CH2_YN3_ML_SPAN 16
#define CH2_YN3_ML_TYPE "altera_avalon_pio"


/*
 * CH2_YN3_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN3_MU altera_avalon_pio
#define CH2_YN3_MU_BASE 0x203240
#define CH2_YN3_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN3_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN3_MU_CAPTURE 1
#define CH2_YN3_MU_DATA_WIDTH 32
#define CH2_YN3_MU_DO_TEST_BENCH_WIRING 0
#define CH2_YN3_MU_DRIVEN_SIM_VALUE 0
#define CH2_YN3_MU_EDGE_TYPE "RISING"
#define CH2_YN3_MU_FREQ 70000000
#define CH2_YN3_MU_HAS_IN 1
#define CH2_YN3_MU_HAS_OUT 0
#define CH2_YN3_MU_HAS_TRI 0
#define CH2_YN3_MU_IRQ -1
#define CH2_YN3_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN3_MU_IRQ_TYPE "NONE"
#define CH2_YN3_MU_NAME "/dev/CH2_YN3_MU"
#define CH2_YN3_MU_RESET_VALUE 0
#define CH2_YN3_MU_SPAN 16
#define CH2_YN3_MU_TYPE "altera_avalon_pio"


/*
 * CH2_YN3_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH2_YN3_U altera_avalon_pio
#define CH2_YN3_U_BASE 0x203250
#define CH2_YN3_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH2_YN3_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH2_YN3_U_CAPTURE 1
#define CH2_YN3_U_DATA_WIDTH 14
#define CH2_YN3_U_DO_TEST_BENCH_WIRING 0
#define CH2_YN3_U_DRIVEN_SIM_VALUE 0
#define CH2_YN3_U_EDGE_TYPE "RISING"
#define CH2_YN3_U_FREQ 70000000
#define CH2_YN3_U_HAS_IN 1
#define CH2_YN3_U_HAS_OUT 0
#define CH2_YN3_U_HAS_TRI 0
#define CH2_YN3_U_IRQ -1
#define CH2_YN3_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH2_YN3_U_IRQ_TYPE "NONE"
#define CH2_YN3_U_NAME "/dev/CH2_YN3_U"
#define CH2_YN3_U_RESET_VALUE 0
#define CH2_YN3_U_SPAN 16
#define CH2_YN3_U_TYPE "altera_avalon_pio"


/*
 * CH3_PEAK_FOUND configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_PEAK_FOUND altera_avalon_pio
#define CH3_PEAK_FOUND_BASE 0x2031e0
#define CH3_PEAK_FOUND_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_PEAK_FOUND_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_PEAK_FOUND_CAPTURE 1
#define CH3_PEAK_FOUND_DATA_WIDTH 1
#define CH3_PEAK_FOUND_DO_TEST_BENCH_WIRING 0
#define CH3_PEAK_FOUND_DRIVEN_SIM_VALUE 0
#define CH3_PEAK_FOUND_EDGE_TYPE "RISING"
#define CH3_PEAK_FOUND_FREQ 70000000
#define CH3_PEAK_FOUND_HAS_IN 1
#define CH3_PEAK_FOUND_HAS_OUT 0
#define CH3_PEAK_FOUND_HAS_TRI 0
#define CH3_PEAK_FOUND_IRQ -1
#define CH3_PEAK_FOUND_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_PEAK_FOUND_IRQ_TYPE "NONE"
#define CH3_PEAK_FOUND_NAME "/dev/CH3_PEAK_FOUND"
#define CH3_PEAK_FOUND_RESET_VALUE 0
#define CH3_PEAK_FOUND_SPAN 16
#define CH3_PEAK_FOUND_TYPE "altera_avalon_pio"


/*
 * CH3_RD_PEAK configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_RD_PEAK altera_avalon_pio
#define CH3_RD_PEAK_BASE 0x2031f0
#define CH3_RD_PEAK_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_RD_PEAK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_RD_PEAK_CAPTURE 0
#define CH3_RD_PEAK_DATA_WIDTH 1
#define CH3_RD_PEAK_DO_TEST_BENCH_WIRING 0
#define CH3_RD_PEAK_DRIVEN_SIM_VALUE 0
#define CH3_RD_PEAK_EDGE_TYPE "NONE"
#define CH3_RD_PEAK_FREQ 70000000
#define CH3_RD_PEAK_HAS_IN 0
#define CH3_RD_PEAK_HAS_OUT 1
#define CH3_RD_PEAK_HAS_TRI 0
#define CH3_RD_PEAK_IRQ -1
#define CH3_RD_PEAK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_RD_PEAK_IRQ_TYPE "NONE"
#define CH3_RD_PEAK_NAME "/dev/CH3_RD_PEAK"
#define CH3_RD_PEAK_RESET_VALUE 0
#define CH3_RD_PEAK_SPAN 16
#define CH3_RD_PEAK_TYPE "altera_avalon_pio"


/*
 * CH3_THRESH configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_THRESH altera_avalon_pio
#define CH3_THRESH_BASE 0x203200
#define CH3_THRESH_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_THRESH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_THRESH_CAPTURE 0
#define CH3_THRESH_DATA_WIDTH 24
#define CH3_THRESH_DO_TEST_BENCH_WIRING 0
#define CH3_THRESH_DRIVEN_SIM_VALUE 0
#define CH3_THRESH_EDGE_TYPE "NONE"
#define CH3_THRESH_FREQ 70000000
#define CH3_THRESH_HAS_IN 0
#define CH3_THRESH_HAS_OUT 1
#define CH3_THRESH_HAS_TRI 0
#define CH3_THRESH_IRQ -1
#define CH3_THRESH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_THRESH_IRQ_TYPE "NONE"
#define CH3_THRESH_NAME "/dev/CH3_THRESH"
#define CH3_THRESH_RESET_VALUE 0
#define CH3_THRESH_SPAN 16
#define CH3_THRESH_TYPE "altera_avalon_pio"


/*
 * CH3_TIME configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_TIME altera_avalon_pio
#define CH3_TIME_BASE 0x2031c0
#define CH3_TIME_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_TIME_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_TIME_CAPTURE 1
#define CH3_TIME_DATA_WIDTH 14
#define CH3_TIME_DO_TEST_BENCH_WIRING 0
#define CH3_TIME_DRIVEN_SIM_VALUE 0
#define CH3_TIME_EDGE_TYPE "RISING"
#define CH3_TIME_FREQ 70000000
#define CH3_TIME_HAS_IN 1
#define CH3_TIME_HAS_OUT 0
#define CH3_TIME_HAS_TRI 0
#define CH3_TIME_IRQ -1
#define CH3_TIME_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_TIME_IRQ_TYPE "NONE"
#define CH3_TIME_NAME "/dev/CH3_TIME"
#define CH3_TIME_RESET_VALUE 0
#define CH3_TIME_SPAN 16
#define CH3_TIME_TYPE "altera_avalon_pio"


/*
 * CH3_TIMER_RST configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_TIMER_RST altera_avalon_pio
#define CH3_TIMER_RST_BASE 0x203210
#define CH3_TIMER_RST_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_TIMER_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_TIMER_RST_CAPTURE 0
#define CH3_TIMER_RST_DATA_WIDTH 1
#define CH3_TIMER_RST_DO_TEST_BENCH_WIRING 0
#define CH3_TIMER_RST_DRIVEN_SIM_VALUE 0
#define CH3_TIMER_RST_EDGE_TYPE "NONE"
#define CH3_TIMER_RST_FREQ 70000000
#define CH3_TIMER_RST_HAS_IN 0
#define CH3_TIMER_RST_HAS_OUT 1
#define CH3_TIMER_RST_HAS_TRI 0
#define CH3_TIMER_RST_IRQ -1
#define CH3_TIMER_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_TIMER_RST_IRQ_TYPE "NONE"
#define CH3_TIMER_RST_NAME "/dev/CH3_TIMER_RST"
#define CH3_TIMER_RST_RESET_VALUE 0
#define CH3_TIMER_RST_SPAN 16
#define CH3_TIMER_RST_TYPE "altera_avalon_pio"


/*
 * CH3_YN1_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN1_L altera_avalon_pio
#define CH3_YN1_L_BASE 0x203130
#define CH3_YN1_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN1_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN1_L_CAPTURE 1
#define CH3_YN1_L_DATA_WIDTH 32
#define CH3_YN1_L_DO_TEST_BENCH_WIRING 0
#define CH3_YN1_L_DRIVEN_SIM_VALUE 0
#define CH3_YN1_L_EDGE_TYPE "RISING"
#define CH3_YN1_L_FREQ 70000000
#define CH3_YN1_L_HAS_IN 1
#define CH3_YN1_L_HAS_OUT 0
#define CH3_YN1_L_HAS_TRI 0
#define CH3_YN1_L_IRQ -1
#define CH3_YN1_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN1_L_IRQ_TYPE "NONE"
#define CH3_YN1_L_NAME "/dev/CH3_YN1_L"
#define CH3_YN1_L_RESET_VALUE 0
#define CH3_YN1_L_SPAN 16
#define CH3_YN1_L_TYPE "altera_avalon_pio"


/*
 * CH3_YN1_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN1_ML altera_avalon_pio
#define CH3_YN1_ML_BASE 0x203110
#define CH3_YN1_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN1_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN1_ML_CAPTURE 1
#define CH3_YN1_ML_DATA_WIDTH 32
#define CH3_YN1_ML_DO_TEST_BENCH_WIRING 0
#define CH3_YN1_ML_DRIVEN_SIM_VALUE 0
#define CH3_YN1_ML_EDGE_TYPE "RISING"
#define CH3_YN1_ML_FREQ 70000000
#define CH3_YN1_ML_HAS_IN 1
#define CH3_YN1_ML_HAS_OUT 0
#define CH3_YN1_ML_HAS_TRI 0
#define CH3_YN1_ML_IRQ -1
#define CH3_YN1_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN1_ML_IRQ_TYPE "NONE"
#define CH3_YN1_ML_NAME "/dev/CH3_YN1_ML"
#define CH3_YN1_ML_RESET_VALUE 0
#define CH3_YN1_ML_SPAN 16
#define CH3_YN1_ML_TYPE "altera_avalon_pio"


/*
 * CH3_YN1_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN1_MU altera_avalon_pio
#define CH3_YN1_MU_BASE 0x203120
#define CH3_YN1_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN1_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN1_MU_CAPTURE 1
#define CH3_YN1_MU_DATA_WIDTH 32
#define CH3_YN1_MU_DO_TEST_BENCH_WIRING 0
#define CH3_YN1_MU_DRIVEN_SIM_VALUE 0
#define CH3_YN1_MU_EDGE_TYPE "RISING"
#define CH3_YN1_MU_FREQ 70000000
#define CH3_YN1_MU_HAS_IN 1
#define CH3_YN1_MU_HAS_OUT 0
#define CH3_YN1_MU_HAS_TRI 0
#define CH3_YN1_MU_IRQ -1
#define CH3_YN1_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN1_MU_IRQ_TYPE "NONE"
#define CH3_YN1_MU_NAME "/dev/CH3_YN1_MU"
#define CH3_YN1_MU_RESET_VALUE 0
#define CH3_YN1_MU_SPAN 16
#define CH3_YN1_MU_TYPE "altera_avalon_pio"


/*
 * CH3_YN1_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN1_U altera_avalon_pio
#define CH3_YN1_U_BASE 0x2031d0
#define CH3_YN1_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN1_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN1_U_CAPTURE 1
#define CH3_YN1_U_DATA_WIDTH 14
#define CH3_YN1_U_DO_TEST_BENCH_WIRING 0
#define CH3_YN1_U_DRIVEN_SIM_VALUE 0
#define CH3_YN1_U_EDGE_TYPE "RISING"
#define CH3_YN1_U_FREQ 70000000
#define CH3_YN1_U_HAS_IN 1
#define CH3_YN1_U_HAS_OUT 0
#define CH3_YN1_U_HAS_TRI 0
#define CH3_YN1_U_IRQ -1
#define CH3_YN1_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN1_U_IRQ_TYPE "NONE"
#define CH3_YN1_U_NAME "/dev/CH3_YN1_U"
#define CH3_YN1_U_RESET_VALUE 0
#define CH3_YN1_U_SPAN 16
#define CH3_YN1_U_TYPE "altera_avalon_pio"


/*
 * CH3_YN2_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN2_L altera_avalon_pio
#define CH3_YN2_L_BASE 0x203170
#define CH3_YN2_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN2_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN2_L_CAPTURE 1
#define CH3_YN2_L_DATA_WIDTH 32
#define CH3_YN2_L_DO_TEST_BENCH_WIRING 0
#define CH3_YN2_L_DRIVEN_SIM_VALUE 0
#define CH3_YN2_L_EDGE_TYPE "RISING"
#define CH3_YN2_L_FREQ 70000000
#define CH3_YN2_L_HAS_IN 1
#define CH3_YN2_L_HAS_OUT 0
#define CH3_YN2_L_HAS_TRI 0
#define CH3_YN2_L_IRQ -1
#define CH3_YN2_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN2_L_IRQ_TYPE "NONE"
#define CH3_YN2_L_NAME "/dev/CH3_YN2_L"
#define CH3_YN2_L_RESET_VALUE 0
#define CH3_YN2_L_SPAN 16
#define CH3_YN2_L_TYPE "altera_avalon_pio"


/*
 * CH3_YN2_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN2_ML altera_avalon_pio
#define CH3_YN2_ML_BASE 0x203160
#define CH3_YN2_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN2_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN2_ML_CAPTURE 1
#define CH3_YN2_ML_DATA_WIDTH 32
#define CH3_YN2_ML_DO_TEST_BENCH_WIRING 0
#define CH3_YN2_ML_DRIVEN_SIM_VALUE 0
#define CH3_YN2_ML_EDGE_TYPE "RISING"
#define CH3_YN2_ML_FREQ 70000000
#define CH3_YN2_ML_HAS_IN 1
#define CH3_YN2_ML_HAS_OUT 0
#define CH3_YN2_ML_HAS_TRI 0
#define CH3_YN2_ML_IRQ -1
#define CH3_YN2_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN2_ML_IRQ_TYPE "NONE"
#define CH3_YN2_ML_NAME "/dev/CH3_YN2_ML"
#define CH3_YN2_ML_RESET_VALUE 0
#define CH3_YN2_ML_SPAN 16
#define CH3_YN2_ML_TYPE "altera_avalon_pio"


/*
 * CH3_YN2_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN2_MU altera_avalon_pio
#define CH3_YN2_MU_BASE 0x203150
#define CH3_YN2_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN2_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN2_MU_CAPTURE 1
#define CH3_YN2_MU_DATA_WIDTH 32
#define CH3_YN2_MU_DO_TEST_BENCH_WIRING 0
#define CH3_YN2_MU_DRIVEN_SIM_VALUE 0
#define CH3_YN2_MU_EDGE_TYPE "RISING"
#define CH3_YN2_MU_FREQ 70000000
#define CH3_YN2_MU_HAS_IN 1
#define CH3_YN2_MU_HAS_OUT 0
#define CH3_YN2_MU_HAS_TRI 0
#define CH3_YN2_MU_IRQ -1
#define CH3_YN2_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN2_MU_IRQ_TYPE "NONE"
#define CH3_YN2_MU_NAME "/dev/CH3_YN2_MU"
#define CH3_YN2_MU_RESET_VALUE 0
#define CH3_YN2_MU_SPAN 16
#define CH3_YN2_MU_TYPE "altera_avalon_pio"


/*
 * CH3_YN2_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN2_U altera_avalon_pio
#define CH3_YN2_U_BASE 0x203140
#define CH3_YN2_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN2_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN2_U_CAPTURE 1
#define CH3_YN2_U_DATA_WIDTH 14
#define CH3_YN2_U_DO_TEST_BENCH_WIRING 0
#define CH3_YN2_U_DRIVEN_SIM_VALUE 0
#define CH3_YN2_U_EDGE_TYPE "RISING"
#define CH3_YN2_U_FREQ 70000000
#define CH3_YN2_U_HAS_IN 1
#define CH3_YN2_U_HAS_OUT 0
#define CH3_YN2_U_HAS_TRI 0
#define CH3_YN2_U_IRQ -1
#define CH3_YN2_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN2_U_IRQ_TYPE "NONE"
#define CH3_YN2_U_NAME "/dev/CH3_YN2_U"
#define CH3_YN2_U_RESET_VALUE 0
#define CH3_YN2_U_SPAN 16
#define CH3_YN2_U_TYPE "altera_avalon_pio"


/*
 * CH3_YN3_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN3_L altera_avalon_pio
#define CH3_YN3_L_BASE 0x2031b0
#define CH3_YN3_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN3_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN3_L_CAPTURE 1
#define CH3_YN3_L_DATA_WIDTH 32
#define CH3_YN3_L_DO_TEST_BENCH_WIRING 0
#define CH3_YN3_L_DRIVEN_SIM_VALUE 0
#define CH3_YN3_L_EDGE_TYPE "RISING"
#define CH3_YN3_L_FREQ 70000000
#define CH3_YN3_L_HAS_IN 1
#define CH3_YN3_L_HAS_OUT 0
#define CH3_YN3_L_HAS_TRI 0
#define CH3_YN3_L_IRQ -1
#define CH3_YN3_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN3_L_IRQ_TYPE "NONE"
#define CH3_YN3_L_NAME "/dev/CH3_YN3_L"
#define CH3_YN3_L_RESET_VALUE 0
#define CH3_YN3_L_SPAN 16
#define CH3_YN3_L_TYPE "altera_avalon_pio"


/*
 * CH3_YN3_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN3_ML altera_avalon_pio
#define CH3_YN3_ML_BASE 0x2031a0
#define CH3_YN3_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN3_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN3_ML_CAPTURE 1
#define CH3_YN3_ML_DATA_WIDTH 32
#define CH3_YN3_ML_DO_TEST_BENCH_WIRING 0
#define CH3_YN3_ML_DRIVEN_SIM_VALUE 0
#define CH3_YN3_ML_EDGE_TYPE "RISING"
#define CH3_YN3_ML_FREQ 70000000
#define CH3_YN3_ML_HAS_IN 1
#define CH3_YN3_ML_HAS_OUT 0
#define CH3_YN3_ML_HAS_TRI 0
#define CH3_YN3_ML_IRQ -1
#define CH3_YN3_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN3_ML_IRQ_TYPE "NONE"
#define CH3_YN3_ML_NAME "/dev/CH3_YN3_ML"
#define CH3_YN3_ML_RESET_VALUE 0
#define CH3_YN3_ML_SPAN 16
#define CH3_YN3_ML_TYPE "altera_avalon_pio"


/*
 * CH3_YN3_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN3_MU altera_avalon_pio
#define CH3_YN3_MU_BASE 0x203190
#define CH3_YN3_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN3_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN3_MU_CAPTURE 1
#define CH3_YN3_MU_DATA_WIDTH 32
#define CH3_YN3_MU_DO_TEST_BENCH_WIRING 0
#define CH3_YN3_MU_DRIVEN_SIM_VALUE 0
#define CH3_YN3_MU_EDGE_TYPE "RISING"
#define CH3_YN3_MU_FREQ 70000000
#define CH3_YN3_MU_HAS_IN 1
#define CH3_YN3_MU_HAS_OUT 0
#define CH3_YN3_MU_HAS_TRI 0
#define CH3_YN3_MU_IRQ -1
#define CH3_YN3_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN3_MU_IRQ_TYPE "NONE"
#define CH3_YN3_MU_NAME "/dev/CH3_YN3_MU"
#define CH3_YN3_MU_RESET_VALUE 0
#define CH3_YN3_MU_SPAN 16
#define CH3_YN3_MU_TYPE "altera_avalon_pio"


/*
 * CH3_YN3_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH3_YN3_U altera_avalon_pio
#define CH3_YN3_U_BASE 0x203180
#define CH3_YN3_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH3_YN3_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH3_YN3_U_CAPTURE 1
#define CH3_YN3_U_DATA_WIDTH 14
#define CH3_YN3_U_DO_TEST_BENCH_WIRING 0
#define CH3_YN3_U_DRIVEN_SIM_VALUE 0
#define CH3_YN3_U_EDGE_TYPE "RISING"
#define CH3_YN3_U_FREQ 70000000
#define CH3_YN3_U_HAS_IN 1
#define CH3_YN3_U_HAS_OUT 0
#define CH3_YN3_U_HAS_TRI 0
#define CH3_YN3_U_IRQ -1
#define CH3_YN3_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH3_YN3_U_IRQ_TYPE "NONE"
#define CH3_YN3_U_NAME "/dev/CH3_YN3_U"
#define CH3_YN3_U_RESET_VALUE 0
#define CH3_YN3_U_SPAN 16
#define CH3_YN3_U_TYPE "altera_avalon_pio"


/*
 * CH4_PEAK_FOUND configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_PEAK_FOUND altera_avalon_pio
#define CH4_PEAK_FOUND_BASE 0x2030d0
#define CH4_PEAK_FOUND_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_PEAK_FOUND_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_PEAK_FOUND_CAPTURE 1
#define CH4_PEAK_FOUND_DATA_WIDTH 1
#define CH4_PEAK_FOUND_DO_TEST_BENCH_WIRING 0
#define CH4_PEAK_FOUND_DRIVEN_SIM_VALUE 0
#define CH4_PEAK_FOUND_EDGE_TYPE "RISING"
#define CH4_PEAK_FOUND_FREQ 70000000
#define CH4_PEAK_FOUND_HAS_IN 1
#define CH4_PEAK_FOUND_HAS_OUT 0
#define CH4_PEAK_FOUND_HAS_TRI 0
#define CH4_PEAK_FOUND_IRQ -1
#define CH4_PEAK_FOUND_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_PEAK_FOUND_IRQ_TYPE "NONE"
#define CH4_PEAK_FOUND_NAME "/dev/CH4_PEAK_FOUND"
#define CH4_PEAK_FOUND_RESET_VALUE 0
#define CH4_PEAK_FOUND_SPAN 16
#define CH4_PEAK_FOUND_TYPE "altera_avalon_pio"


/*
 * CH4_RD_PEAK configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_RD_PEAK altera_avalon_pio
#define CH4_RD_PEAK_BASE 0x2030e0
#define CH4_RD_PEAK_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_RD_PEAK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_RD_PEAK_CAPTURE 0
#define CH4_RD_PEAK_DATA_WIDTH 1
#define CH4_RD_PEAK_DO_TEST_BENCH_WIRING 0
#define CH4_RD_PEAK_DRIVEN_SIM_VALUE 0
#define CH4_RD_PEAK_EDGE_TYPE "NONE"
#define CH4_RD_PEAK_FREQ 70000000
#define CH4_RD_PEAK_HAS_IN 0
#define CH4_RD_PEAK_HAS_OUT 1
#define CH4_RD_PEAK_HAS_TRI 0
#define CH4_RD_PEAK_IRQ -1
#define CH4_RD_PEAK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_RD_PEAK_IRQ_TYPE "NONE"
#define CH4_RD_PEAK_NAME "/dev/CH4_RD_PEAK"
#define CH4_RD_PEAK_RESET_VALUE 0
#define CH4_RD_PEAK_SPAN 16
#define CH4_RD_PEAK_TYPE "altera_avalon_pio"


/*
 * CH4_THRESH configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_THRESH altera_avalon_pio
#define CH4_THRESH_BASE 0x2030f0
#define CH4_THRESH_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_THRESH_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_THRESH_CAPTURE 0
#define CH4_THRESH_DATA_WIDTH 24
#define CH4_THRESH_DO_TEST_BENCH_WIRING 0
#define CH4_THRESH_DRIVEN_SIM_VALUE 0
#define CH4_THRESH_EDGE_TYPE "NONE"
#define CH4_THRESH_FREQ 70000000
#define CH4_THRESH_HAS_IN 0
#define CH4_THRESH_HAS_OUT 1
#define CH4_THRESH_HAS_TRI 0
#define CH4_THRESH_IRQ -1
#define CH4_THRESH_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_THRESH_IRQ_TYPE "NONE"
#define CH4_THRESH_NAME "/dev/CH4_THRESH"
#define CH4_THRESH_RESET_VALUE 0
#define CH4_THRESH_SPAN 16
#define CH4_THRESH_TYPE "altera_avalon_pio"


/*
 * CH4_TIME configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_TIME altera_avalon_pio
#define CH4_TIME_BASE 0x2030c0
#define CH4_TIME_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_TIME_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_TIME_CAPTURE 1
#define CH4_TIME_DATA_WIDTH 14
#define CH4_TIME_DO_TEST_BENCH_WIRING 0
#define CH4_TIME_DRIVEN_SIM_VALUE 0
#define CH4_TIME_EDGE_TYPE "RISING"
#define CH4_TIME_FREQ 70000000
#define CH4_TIME_HAS_IN 1
#define CH4_TIME_HAS_OUT 0
#define CH4_TIME_HAS_TRI 0
#define CH4_TIME_IRQ -1
#define CH4_TIME_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_TIME_IRQ_TYPE "NONE"
#define CH4_TIME_NAME "/dev/CH4_TIME"
#define CH4_TIME_RESET_VALUE 0
#define CH4_TIME_SPAN 16
#define CH4_TIME_TYPE "altera_avalon_pio"


/*
 * CH4_TIMER_RST configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_TIMER_RST altera_avalon_pio
#define CH4_TIMER_RST_BASE 0x203100
#define CH4_TIMER_RST_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_TIMER_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_TIMER_RST_CAPTURE 0
#define CH4_TIMER_RST_DATA_WIDTH 1
#define CH4_TIMER_RST_DO_TEST_BENCH_WIRING 0
#define CH4_TIMER_RST_DRIVEN_SIM_VALUE 0
#define CH4_TIMER_RST_EDGE_TYPE "NONE"
#define CH4_TIMER_RST_FREQ 70000000
#define CH4_TIMER_RST_HAS_IN 0
#define CH4_TIMER_RST_HAS_OUT 1
#define CH4_TIMER_RST_HAS_TRI 0
#define CH4_TIMER_RST_IRQ -1
#define CH4_TIMER_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_TIMER_RST_IRQ_TYPE "NONE"
#define CH4_TIMER_RST_NAME "/dev/CH4_TIMER_RST"
#define CH4_TIMER_RST_RESET_VALUE 0
#define CH4_TIMER_RST_SPAN 16
#define CH4_TIMER_RST_TYPE "altera_avalon_pio"


/*
 * CH4_YN1_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN1_L altera_avalon_pio
#define CH4_YN1_L_BASE 0x203080
#define CH4_YN1_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN1_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN1_L_CAPTURE 1
#define CH4_YN1_L_DATA_WIDTH 32
#define CH4_YN1_L_DO_TEST_BENCH_WIRING 0
#define CH4_YN1_L_DRIVEN_SIM_VALUE 0
#define CH4_YN1_L_EDGE_TYPE "RISING"
#define CH4_YN1_L_FREQ 70000000
#define CH4_YN1_L_HAS_IN 1
#define CH4_YN1_L_HAS_OUT 0
#define CH4_YN1_L_HAS_TRI 0
#define CH4_YN1_L_IRQ -1
#define CH4_YN1_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN1_L_IRQ_TYPE "NONE"
#define CH4_YN1_L_NAME "/dev/CH4_YN1_L"
#define CH4_YN1_L_RESET_VALUE 0
#define CH4_YN1_L_SPAN 16
#define CH4_YN1_L_TYPE "altera_avalon_pio"


/*
 * CH4_YN1_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN1_ML altera_avalon_pio
#define CH4_YN1_ML_BASE 0x203090
#define CH4_YN1_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN1_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN1_ML_CAPTURE 1
#define CH4_YN1_ML_DATA_WIDTH 32
#define CH4_YN1_ML_DO_TEST_BENCH_WIRING 0
#define CH4_YN1_ML_DRIVEN_SIM_VALUE 0
#define CH4_YN1_ML_EDGE_TYPE "RISING"
#define CH4_YN1_ML_FREQ 70000000
#define CH4_YN1_ML_HAS_IN 1
#define CH4_YN1_ML_HAS_OUT 0
#define CH4_YN1_ML_HAS_TRI 0
#define CH4_YN1_ML_IRQ -1
#define CH4_YN1_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN1_ML_IRQ_TYPE "NONE"
#define CH4_YN1_ML_NAME "/dev/CH4_YN1_ML"
#define CH4_YN1_ML_RESET_VALUE 0
#define CH4_YN1_ML_SPAN 16
#define CH4_YN1_ML_TYPE "altera_avalon_pio"


/*
 * CH4_YN1_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN1_MU altera_avalon_pio
#define CH4_YN1_MU_BASE 0x2030a0
#define CH4_YN1_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN1_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN1_MU_CAPTURE 1
#define CH4_YN1_MU_DATA_WIDTH 32
#define CH4_YN1_MU_DO_TEST_BENCH_WIRING 0
#define CH4_YN1_MU_DRIVEN_SIM_VALUE 0
#define CH4_YN1_MU_EDGE_TYPE "RISING"
#define CH4_YN1_MU_FREQ 70000000
#define CH4_YN1_MU_HAS_IN 1
#define CH4_YN1_MU_HAS_OUT 0
#define CH4_YN1_MU_HAS_TRI 0
#define CH4_YN1_MU_IRQ -1
#define CH4_YN1_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN1_MU_IRQ_TYPE "NONE"
#define CH4_YN1_MU_NAME "/dev/CH4_YN1_MU"
#define CH4_YN1_MU_RESET_VALUE 0
#define CH4_YN1_MU_SPAN 16
#define CH4_YN1_MU_TYPE "altera_avalon_pio"


/*
 * CH4_YN1_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN1_U altera_avalon_pio
#define CH4_YN1_U_BASE 0x2030b0
#define CH4_YN1_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN1_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN1_U_CAPTURE 1
#define CH4_YN1_U_DATA_WIDTH 14
#define CH4_YN1_U_DO_TEST_BENCH_WIRING 0
#define CH4_YN1_U_DRIVEN_SIM_VALUE 0
#define CH4_YN1_U_EDGE_TYPE "RISING"
#define CH4_YN1_U_FREQ 70000000
#define CH4_YN1_U_HAS_IN 1
#define CH4_YN1_U_HAS_OUT 0
#define CH4_YN1_U_HAS_TRI 0
#define CH4_YN1_U_IRQ -1
#define CH4_YN1_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN1_U_IRQ_TYPE "NONE"
#define CH4_YN1_U_NAME "/dev/CH4_YN1_U"
#define CH4_YN1_U_RESET_VALUE 0
#define CH4_YN1_U_SPAN 16
#define CH4_YN1_U_TYPE "altera_avalon_pio"


/*
 * CH4_YN2_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN2_L altera_avalon_pio
#define CH4_YN2_L_BASE 0x203040
#define CH4_YN2_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN2_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN2_L_CAPTURE 1
#define CH4_YN2_L_DATA_WIDTH 32
#define CH4_YN2_L_DO_TEST_BENCH_WIRING 0
#define CH4_YN2_L_DRIVEN_SIM_VALUE 0
#define CH4_YN2_L_EDGE_TYPE "RISING"
#define CH4_YN2_L_FREQ 70000000
#define CH4_YN2_L_HAS_IN 1
#define CH4_YN2_L_HAS_OUT 0
#define CH4_YN2_L_HAS_TRI 0
#define CH4_YN2_L_IRQ -1
#define CH4_YN2_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN2_L_IRQ_TYPE "NONE"
#define CH4_YN2_L_NAME "/dev/CH4_YN2_L"
#define CH4_YN2_L_RESET_VALUE 0
#define CH4_YN2_L_SPAN 16
#define CH4_YN2_L_TYPE "altera_avalon_pio"


/*
 * CH4_YN2_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN2_ML altera_avalon_pio
#define CH4_YN2_ML_BASE 0x203050
#define CH4_YN2_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN2_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN2_ML_CAPTURE 1
#define CH4_YN2_ML_DATA_WIDTH 32
#define CH4_YN2_ML_DO_TEST_BENCH_WIRING 0
#define CH4_YN2_ML_DRIVEN_SIM_VALUE 0
#define CH4_YN2_ML_EDGE_TYPE "RISING"
#define CH4_YN2_ML_FREQ 70000000
#define CH4_YN2_ML_HAS_IN 1
#define CH4_YN2_ML_HAS_OUT 0
#define CH4_YN2_ML_HAS_TRI 0
#define CH4_YN2_ML_IRQ -1
#define CH4_YN2_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN2_ML_IRQ_TYPE "NONE"
#define CH4_YN2_ML_NAME "/dev/CH4_YN2_ML"
#define CH4_YN2_ML_RESET_VALUE 0
#define CH4_YN2_ML_SPAN 16
#define CH4_YN2_ML_TYPE "altera_avalon_pio"


/*
 * CH4_YN2_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN2_MU altera_avalon_pio
#define CH4_YN2_MU_BASE 0x203060
#define CH4_YN2_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN2_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN2_MU_CAPTURE 1
#define CH4_YN2_MU_DATA_WIDTH 32
#define CH4_YN2_MU_DO_TEST_BENCH_WIRING 0
#define CH4_YN2_MU_DRIVEN_SIM_VALUE 0
#define CH4_YN2_MU_EDGE_TYPE "RISING"
#define CH4_YN2_MU_FREQ 70000000
#define CH4_YN2_MU_HAS_IN 1
#define CH4_YN2_MU_HAS_OUT 0
#define CH4_YN2_MU_HAS_TRI 0
#define CH4_YN2_MU_IRQ -1
#define CH4_YN2_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN2_MU_IRQ_TYPE "NONE"
#define CH4_YN2_MU_NAME "/dev/CH4_YN2_MU"
#define CH4_YN2_MU_RESET_VALUE 0
#define CH4_YN2_MU_SPAN 16
#define CH4_YN2_MU_TYPE "altera_avalon_pio"


/*
 * CH4_YN2_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN2_U altera_avalon_pio
#define CH4_YN2_U_BASE 0x203070
#define CH4_YN2_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN2_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN2_U_CAPTURE 1
#define CH4_YN2_U_DATA_WIDTH 14
#define CH4_YN2_U_DO_TEST_BENCH_WIRING 0
#define CH4_YN2_U_DRIVEN_SIM_VALUE 0
#define CH4_YN2_U_EDGE_TYPE "RISING"
#define CH4_YN2_U_FREQ 70000000
#define CH4_YN2_U_HAS_IN 1
#define CH4_YN2_U_HAS_OUT 0
#define CH4_YN2_U_HAS_TRI 0
#define CH4_YN2_U_IRQ -1
#define CH4_YN2_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN2_U_IRQ_TYPE "NONE"
#define CH4_YN2_U_NAME "/dev/CH4_YN2_U"
#define CH4_YN2_U_RESET_VALUE 0
#define CH4_YN2_U_SPAN 16
#define CH4_YN2_U_TYPE "altera_avalon_pio"


/*
 * CH4_YN3_L configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN3_L altera_avalon_pio
#define CH4_YN3_L_BASE 0x203000
#define CH4_YN3_L_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN3_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN3_L_CAPTURE 1
#define CH4_YN3_L_DATA_WIDTH 32
#define CH4_YN3_L_DO_TEST_BENCH_WIRING 0
#define CH4_YN3_L_DRIVEN_SIM_VALUE 0
#define CH4_YN3_L_EDGE_TYPE "RISING"
#define CH4_YN3_L_FREQ 70000000
#define CH4_YN3_L_HAS_IN 1
#define CH4_YN3_L_HAS_OUT 0
#define CH4_YN3_L_HAS_TRI 0
#define CH4_YN3_L_IRQ -1
#define CH4_YN3_L_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN3_L_IRQ_TYPE "NONE"
#define CH4_YN3_L_NAME "/dev/CH4_YN3_L"
#define CH4_YN3_L_RESET_VALUE 0
#define CH4_YN3_L_SPAN 16
#define CH4_YN3_L_TYPE "altera_avalon_pio"


/*
 * CH4_YN3_ML configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN3_ML altera_avalon_pio
#define CH4_YN3_ML_BASE 0x203010
#define CH4_YN3_ML_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN3_ML_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN3_ML_CAPTURE 1
#define CH4_YN3_ML_DATA_WIDTH 32
#define CH4_YN3_ML_DO_TEST_BENCH_WIRING 0
#define CH4_YN3_ML_DRIVEN_SIM_VALUE 0
#define CH4_YN3_ML_EDGE_TYPE "RISING"
#define CH4_YN3_ML_FREQ 70000000
#define CH4_YN3_ML_HAS_IN 1
#define CH4_YN3_ML_HAS_OUT 0
#define CH4_YN3_ML_HAS_TRI 0
#define CH4_YN3_ML_IRQ -1
#define CH4_YN3_ML_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN3_ML_IRQ_TYPE "NONE"
#define CH4_YN3_ML_NAME "/dev/CH4_YN3_ML"
#define CH4_YN3_ML_RESET_VALUE 0
#define CH4_YN3_ML_SPAN 16
#define CH4_YN3_ML_TYPE "altera_avalon_pio"


/*
 * CH4_YN3_MU configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN3_MU altera_avalon_pio
#define CH4_YN3_MU_BASE 0x203020
#define CH4_YN3_MU_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN3_MU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN3_MU_CAPTURE 1
#define CH4_YN3_MU_DATA_WIDTH 32
#define CH4_YN3_MU_DO_TEST_BENCH_WIRING 0
#define CH4_YN3_MU_DRIVEN_SIM_VALUE 0
#define CH4_YN3_MU_EDGE_TYPE "RISING"
#define CH4_YN3_MU_FREQ 70000000
#define CH4_YN3_MU_HAS_IN 1
#define CH4_YN3_MU_HAS_OUT 0
#define CH4_YN3_MU_HAS_TRI 0
#define CH4_YN3_MU_IRQ -1
#define CH4_YN3_MU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN3_MU_IRQ_TYPE "NONE"
#define CH4_YN3_MU_NAME "/dev/CH4_YN3_MU"
#define CH4_YN3_MU_RESET_VALUE 0
#define CH4_YN3_MU_SPAN 16
#define CH4_YN3_MU_TYPE "altera_avalon_pio"


/*
 * CH4_YN3_U configuration
 *
 */

#define ALT_MODULE_CLASS_CH4_YN3_U altera_avalon_pio
#define CH4_YN3_U_BASE 0x203030
#define CH4_YN3_U_BIT_CLEARING_EDGE_REGISTER 0
#define CH4_YN3_U_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CH4_YN3_U_CAPTURE 1
#define CH4_YN3_U_DATA_WIDTH 14
#define CH4_YN3_U_DO_TEST_BENCH_WIRING 0
#define CH4_YN3_U_DRIVEN_SIM_VALUE 0
#define CH4_YN3_U_EDGE_TYPE "RISING"
#define CH4_YN3_U_FREQ 70000000
#define CH4_YN3_U_HAS_IN 1
#define CH4_YN3_U_HAS_OUT 0
#define CH4_YN3_U_HAS_TRI 0
#define CH4_YN3_U_IRQ -1
#define CH4_YN3_U_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CH4_YN3_U_IRQ_TYPE "NONE"
#define CH4_YN3_U_NAME "/dev/CH4_YN3_U"
#define CH4_YN3_U_RESET_VALUE 0
#define CH4_YN3_U_SPAN 16
#define CH4_YN3_U_TYPE "altera_avalon_pio"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x202820
#define ALT_CPU_CPU_FREQ 70000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x16
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x200020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 70000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x16
#define ALT_CPU_NAME "NIOS_CPU"
#define ALT_CPU_RESET_ADDR 0x200000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x202820
#define NIOS2_CPU_FREQ 70000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x16
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x200020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x16
#define NIOS2_RESET_ADDR 0x200000


/*
 * DETECTOR_ON configuration
 *
 */

#define ALT_MODULE_CLASS_DETECTOR_ON altera_avalon_pio
#define DETECTOR_ON_BASE 0x203570
#define DETECTOR_ON_BIT_CLEARING_EDGE_REGISTER 0
#define DETECTOR_ON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DETECTOR_ON_CAPTURE 0
#define DETECTOR_ON_DATA_WIDTH 1
#define DETECTOR_ON_DO_TEST_BENCH_WIRING 0
#define DETECTOR_ON_DRIVEN_SIM_VALUE 0
#define DETECTOR_ON_EDGE_TYPE "NONE"
#define DETECTOR_ON_FREQ 70000000
#define DETECTOR_ON_HAS_IN 0
#define DETECTOR_ON_HAS_OUT 1
#define DETECTOR_ON_HAS_TRI 0
#define DETECTOR_ON_IRQ -1
#define DETECTOR_ON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DETECTOR_ON_IRQ_TYPE "NONE"
#define DETECTOR_ON_NAME "/dev/DETECTOR_ON"
#define DETECTOR_ON_RESET_VALUE 0
#define DETECTOR_ON_SPAN 16
#define DETECTOR_ON_TYPE "altera_avalon_pio"


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_LCD_16207
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_NIOS2_QSYS


/*
 * FIFO_ADC_DATA configuration
 *
 */

#define ALT_MODULE_CLASS_FIFO_ADC_DATA altera_avalon_pio
#define FIFO_ADC_DATA_BASE 0x2035c0
#define FIFO_ADC_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define FIFO_ADC_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FIFO_ADC_DATA_CAPTURE 0
#define FIFO_ADC_DATA_DATA_WIDTH 16
#define FIFO_ADC_DATA_DO_TEST_BENCH_WIRING 0
#define FIFO_ADC_DATA_DRIVEN_SIM_VALUE 0
#define FIFO_ADC_DATA_EDGE_TYPE "NONE"
#define FIFO_ADC_DATA_FREQ 70000000
#define FIFO_ADC_DATA_HAS_IN 0
#define FIFO_ADC_DATA_HAS_OUT 1
#define FIFO_ADC_DATA_HAS_TRI 0
#define FIFO_ADC_DATA_IRQ -1
#define FIFO_ADC_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_ADC_DATA_IRQ_TYPE "NONE"
#define FIFO_ADC_DATA_NAME "/dev/FIFO_ADC_DATA"
#define FIFO_ADC_DATA_RESET_VALUE 0
#define FIFO_ADC_DATA_SPAN 16
#define FIFO_ADC_DATA_TYPE "altera_avalon_pio"


/*
 * FIFO_ADC_DATA_VALID configuration
 *
 */

#define ALT_MODULE_CLASS_FIFO_ADC_DATA_VALID altera_avalon_pio
#define FIFO_ADC_DATA_VALID_BASE 0x2035b0
#define FIFO_ADC_DATA_VALID_BIT_CLEARING_EDGE_REGISTER 0
#define FIFO_ADC_DATA_VALID_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FIFO_ADC_DATA_VALID_CAPTURE 0
#define FIFO_ADC_DATA_VALID_DATA_WIDTH 1
#define FIFO_ADC_DATA_VALID_DO_TEST_BENCH_WIRING 0
#define FIFO_ADC_DATA_VALID_DRIVEN_SIM_VALUE 0
#define FIFO_ADC_DATA_VALID_EDGE_TYPE "NONE"
#define FIFO_ADC_DATA_VALID_FREQ 70000000
#define FIFO_ADC_DATA_VALID_HAS_IN 0
#define FIFO_ADC_DATA_VALID_HAS_OUT 1
#define FIFO_ADC_DATA_VALID_HAS_TRI 0
#define FIFO_ADC_DATA_VALID_IRQ -1
#define FIFO_ADC_DATA_VALID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_ADC_DATA_VALID_IRQ_TYPE "NONE"
#define FIFO_ADC_DATA_VALID_NAME "/dev/FIFO_ADC_DATA_VALID"
#define FIFO_ADC_DATA_VALID_RESET_VALUE 0
#define FIFO_ADC_DATA_VALID_SPAN 16
#define FIFO_ADC_DATA_VALID_TYPE "altera_avalon_pio"


/*
 * FIFO_RST configuration
 *
 */

#define ALT_MODULE_CLASS_FIFO_RST altera_avalon_pio
#define FIFO_RST_BASE 0x2035a0
#define FIFO_RST_BIT_CLEARING_EDGE_REGISTER 0
#define FIFO_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FIFO_RST_CAPTURE 0
#define FIFO_RST_DATA_WIDTH 1
#define FIFO_RST_DO_TEST_BENCH_WIRING 0
#define FIFO_RST_DRIVEN_SIM_VALUE 0
#define FIFO_RST_EDGE_TYPE "NONE"
#define FIFO_RST_FREQ 70000000
#define FIFO_RST_HAS_IN 0
#define FIFO_RST_HAS_OUT 1
#define FIFO_RST_HAS_TRI 0
#define FIFO_RST_IRQ -1
#define FIFO_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_RST_IRQ_TYPE "NONE"
#define FIFO_RST_NAME "/dev/FIFO_RST"
#define FIFO_RST_RESET_VALUE 0
#define FIFO_RST_SPAN 16
#define FIFO_RST_TYPE "altera_avalon_pio"


/*
 * JTAG_UART configuration
 *
 */

#define ALT_MODULE_CLASS_JTAG_UART altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x2035f0
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/JTAG_UART"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * LCD configuration
 *
 */

#define ALT_MODULE_CLASS_LCD altera_avalon_lcd_16207
#define LCD_BASE 0x2035e0
#define LCD_IRQ -1
#define LCD_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_NAME "/dev/LCD"
#define LCD_SPAN 16
#define LCD_TYPE "altera_avalon_lcd_16207"


/*
 * MENU configuration
 *
 */

#define ALT_MODULE_CLASS_MENU altera_avalon_pio
#define MENU_BASE 0x203540
#define MENU_BIT_CLEARING_EDGE_REGISTER 0
#define MENU_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MENU_CAPTURE 1
#define MENU_DATA_WIDTH 1
#define MENU_DO_TEST_BENCH_WIRING 0
#define MENU_DRIVEN_SIM_VALUE 0
#define MENU_EDGE_TYPE "RISING"
#define MENU_FREQ 70000000
#define MENU_HAS_IN 1
#define MENU_HAS_OUT 0
#define MENU_HAS_TRI 0
#define MENU_IRQ -1
#define MENU_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MENU_IRQ_TYPE "NONE"
#define MENU_NAME "/dev/MENU"
#define MENU_RESET_VALUE 0
#define MENU_SPAN 16
#define MENU_TYPE "altera_avalon_pio"


/*
 * MENU_DOWN configuration
 *
 */

#define ALT_MODULE_CLASS_MENU_DOWN altera_avalon_pio
#define MENU_DOWN_BASE 0x203560
#define MENU_DOWN_BIT_CLEARING_EDGE_REGISTER 0
#define MENU_DOWN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MENU_DOWN_CAPTURE 0
#define MENU_DOWN_DATA_WIDTH 1
#define MENU_DOWN_DO_TEST_BENCH_WIRING 0
#define MENU_DOWN_DRIVEN_SIM_VALUE 0
#define MENU_DOWN_EDGE_TYPE "NONE"
#define MENU_DOWN_FREQ 70000000
#define MENU_DOWN_HAS_IN 1
#define MENU_DOWN_HAS_OUT 0
#define MENU_DOWN_HAS_TRI 0
#define MENU_DOWN_IRQ -1
#define MENU_DOWN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MENU_DOWN_IRQ_TYPE "NONE"
#define MENU_DOWN_NAME "/dev/MENU_DOWN"
#define MENU_DOWN_RESET_VALUE 0
#define MENU_DOWN_SPAN 16
#define MENU_DOWN_TYPE "altera_avalon_pio"


/*
 * MENU_UP configuration
 *
 */

#define ALT_MODULE_CLASS_MENU_UP altera_avalon_pio
#define MENU_UP_BASE 0x203550
#define MENU_UP_BIT_CLEARING_EDGE_REGISTER 0
#define MENU_UP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MENU_UP_CAPTURE 1
#define MENU_UP_DATA_WIDTH 1
#define MENU_UP_DO_TEST_BENCH_WIRING 0
#define MENU_UP_DRIVEN_SIM_VALUE 0
#define MENU_UP_EDGE_TYPE "RISING"
#define MENU_UP_FREQ 70000000
#define MENU_UP_HAS_IN 1
#define MENU_UP_HAS_OUT 0
#define MENU_UP_HAS_TRI 0
#define MENU_UP_IRQ -1
#define MENU_UP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MENU_UP_IRQ_TYPE "NONE"
#define MENU_UP_NAME "/dev/MENU_UP"
#define MENU_UP_RESET_VALUE 0
#define MENU_UP_SPAN 16
#define MENU_UP_TYPE "altera_avalon_pio"


/*
 * RAM configuration
 *
 */

#define ALT_MODULE_CLASS_RAM altera_avalon_onchip_memory2
#define RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RAM_BASE 0x200000
#define RAM_CONTENTS_INFO ""
#define RAM_DUAL_PORT 0
#define RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define RAM_INIT_CONTENTS_FILE "NIOS_SYSTEMV3_RAM"
#define RAM_INIT_MEM_CONTENT 1
#define RAM_INSTANCE_ID "NONE"
#define RAM_IRQ -1
#define RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RAM_NAME "/dev/RAM"
#define RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RAM_RAM_BLOCK_TYPE "AUTO"
#define RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define RAM_SINGLE_CLOCK_OP 0
#define RAM_SIZE_MULTIPLE 1
#define RAM_SIZE_VALUE 8192
#define RAM_SPAN 8192
#define RAM_TYPE "altera_avalon_onchip_memory2"
#define RAM_WRITABLE 1


/*
 * SSRAM configuration
 *
 */

#define ALT_MODULE_CLASS_SSRAM altera_generic_tristate_controller
#define SSRAM_BASE 0x0
#define SSRAM_IRQ -1
#define SSRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSRAM_NAME "/dev/SSRAM"
#define SSRAM_SPAN 2097152
#define SSRAM_SRAM_MEMORY_SIZE 2
#define SSRAM_SRAM_MEMORY_UNITS 1048576
#define SSRAM_SSRAM_DATA_WIDTH 32
#define SSRAM_SSRAM_READ_LATENCY 2
#define SSRAM_TYPE "altera_generic_tristate_controller"


/*
 * SUBTRACTOR_ON configuration
 *
 */

#define ALT_MODULE_CLASS_SUBTRACTOR_ON altera_avalon_pio
#define SUBTRACTOR_ON_BASE 0x203590
#define SUBTRACTOR_ON_BIT_CLEARING_EDGE_REGISTER 0
#define SUBTRACTOR_ON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SUBTRACTOR_ON_CAPTURE 0
#define SUBTRACTOR_ON_DATA_WIDTH 1
#define SUBTRACTOR_ON_DO_TEST_BENCH_WIRING 0
#define SUBTRACTOR_ON_DRIVEN_SIM_VALUE 0
#define SUBTRACTOR_ON_EDGE_TYPE "NONE"
#define SUBTRACTOR_ON_FREQ 70000000
#define SUBTRACTOR_ON_HAS_IN 0
#define SUBTRACTOR_ON_HAS_OUT 1
#define SUBTRACTOR_ON_HAS_TRI 0
#define SUBTRACTOR_ON_IRQ -1
#define SUBTRACTOR_ON_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SUBTRACTOR_ON_IRQ_TYPE "NONE"
#define SUBTRACTOR_ON_NAME "/dev/SUBTRACTOR_ON"
#define SUBTRACTOR_ON_RESET_VALUE 0
#define SUBTRACTOR_ON_SPAN 16
#define SUBTRACTOR_ON_TYPE "altera_avalon_pio"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone II"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/JTAG_UART"
#define ALT_STDERR_BASE 0x2035f0
#define ALT_STDERR_DEV JTAG_UART
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/JTAG_UART"
#define ALT_STDIN_BASE 0x2035f0
#define ALT_STDIN_DEV JTAG_UART
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/JTAG_UART"
#define ALT_STDOUT_BASE 0x2035f0
#define ALT_STDOUT_DEV JTAG_UART
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "NIOS_SYSTEMV3"


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none

#endif /* __SYSTEM_H_ */
